/* LitePix v4.18 worker: builds serialized local triangle BVHs off the main thread. */
'use strict';
function boundsTri(pos,idx,t){const k=t*3,ia=idx[k]*3,ib=idx[k+1]*3,ic=idx[k+2]*3;const min=[Math.min(pos[ia],pos[ib],pos[ic]),Math.min(pos[ia+1],pos[ib+1],pos[ic+1]),Math.min(pos[ia+2],pos[ib+2],pos[ic+2])],max=[Math.max(pos[ia],pos[ib],pos[ic]),Math.max(pos[ia+1],pos[ib+1],pos[ic+1]),Math.max(pos[ia+2],pos[ib+2],pos[ic+2])];return{min,max,c:[(min[0]+max[0])*.5,(min[1]+max[1])*.5,(min[2]+max[2])*.5]};}
const area=(mn,mx)=>{const x=Math.max(0,mx[0]-mn[0]),y=Math.max(0,mx[1]-mn[1]),z=Math.max(0,mx[2]-mn[2]);return 2*(x*y+y*z+z*x);};
function build(positions,indices,maxLeaf=4,bins=16){const triCount=indices.length/3,prims=new Array(triCount);for(let t=0;t<triCount;t++)prims[t]=boundsTri(positions,indices,t);const order=Array.from({length:triCount},(_,i)=>i),nodes=[];
 function rec(start,count){let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity],cmn=[Infinity,Infinity,Infinity],cmx=[-Infinity,-Infinity,-Infinity];for(let q=start;q<start+count;q++){const b=prims[order[q]];for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);cmn[k]=Math.min(cmn[k],b.c[k]);cmx[k]=Math.max(cmx[k],b.c[k]);}}const ni=nodes.length,n={bounds:{min:mn,max:mx},leaf:false,start:0,count:0,left:-1,right:-1};nodes.push(n);if(count<=maxLeaf){n.leaf=true;n.start=start;n.count=count;return ni;}let bestAxis=-1,bestSplit=-1,bestCost=Infinity;for(let ax=0;ax<3;ax++){const span=cmx[ax]-cmn[ax];if(span<=1e-12)continue;const bc=new Int32Array(bins),bmn=Array.from({length:bins},()=>[Infinity,Infinity,Infinity]),bmx=Array.from({length:bins},()=>[-Infinity,-Infinity,-Infinity]);for(let q=start;q<start+count;q++){const p=prims[order[q]],bi=Math.min(bins-1,Math.max(0,Math.floor((p.c[ax]-cmn[ax])/span*bins)));bc[bi]++;for(let k=0;k<3;k++){bmn[bi][k]=Math.min(bmn[bi][k],p.min[k]);bmx[bi][k]=Math.max(bmx[bi][k],p.max[k]);}}const lc=new Int32Array(bins),rc=new Int32Array(bins),la=new Float64Array(bins),ra=new Float64Array(bins);let c=0,lmn=[Infinity,Infinity,Infinity],lmx=[-Infinity,-Infinity,-Infinity];for(let b=0;b<bins;b++){c+=bc[b];lc[b]=c;if(bc[b])for(let k=0;k<3;k++){lmn[k]=Math.min(lmn[k],bmn[b][k]);lmx[k]=Math.max(lmx[k],bmx[b][k]);}la[b]=c?area(lmn,lmx):0;}c=0;let rmn=[Infinity,Infinity,Infinity],rmx=[-Infinity,-Infinity,-Infinity];for(let b=bins-1;b>=0;b--){c+=bc[b];rc[b]=c;if(bc[b])for(let k=0;k<3;k++){rmn[k]=Math.min(rmn[k],bmn[b][k]);rmx[k]=Math.max(rmx[k],bmx[b][k]);}ra[b]=c?area(rmn,rmx):0;}for(let b=0;b<bins-1;b++){if(!lc[b]||!rc[b+1])continue;const cost=la[b]*lc[b]+ra[b+1]*rc[b+1];if(cost<bestCost){bestCost=cost;bestAxis=ax;bestSplit=b;}}}
 if(bestAxis<0){bestAxis=0;let sp=cmx[0]-cmn[0];for(let k=1;k<3;k++){const s=cmx[k]-cmn[k];if(s>sp){sp=s;bestAxis=k;}}order.slice(start,start+count).sort((a,b)=>prims[a].c[bestAxis]-prims[b].c[bestAxis]).forEach((v,j)=>order[start+j]=v);const m=start+(count>>1);n.left=rec(start,m-start);n.right=rec(m,start+count-m);return ni;}
 const span=cmx[bestAxis]-cmn[bestAxis],cut=cmn[bestAxis]+span*((bestSplit+1)/bins);let i=start,j=start+count-1;while(i<=j){if(prims[order[i]].c[bestAxis]<cut)i++;else{const z=order[i];order[i]=order[j];order[j]=z;j--;}}let mid=i;if(mid===start||mid===start+count){order.slice(start,start+count).sort((a,b)=>prims[a].c[bestAxis]-prims[b].c[bestAxis]).forEach((v,k)=>order[start+k]=v);mid=start+(count>>1);}n.left=rec(start,mid-start);n.right=rec(mid,start+count-mid);return ni;}
 if(triCount)rec(0,triCount);return{nodes,indices:order,triangleCount:triCount};}
self.onmessage=e=>{try{const d=e.data||{};if(d.type!=='build')return;const t=performance.now(),positions=new Float32Array(d.positions),indices=new Uint32Array(d.indices),bvh=build(positions,indices,d.maxLeaf||4,d.bins||16);self.postMessage({id:d.id,ok:true,key:d.key,bvh,buildMs:performance.now()-t});}catch(err){self.postMessage({id:e.data?.id,ok:false,error:String(err?.stack||err)});}};