(function(root){'use strict';
const LP=root.LitePixNative=root.LitePixNative||{},C5=LP.Core5;if(!C5)throw new Error('LitePix Core5 base missing');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lum=c=>.2126*(c?.[0]||0)+.7152*(c?.[1]||0)+.0722*(c?.[2]||0);
class WeightedReservoir428 extends C5.Reservoir{constructor(){super();this.source='none';this.age=0;}updateTagged(sample,weight,source,rng=Math.random){const prev=this.sample;super.update(sample,weight,rng);if(this.sample!==prev||this.sample===sample)this.source=source||'current';return this;}clone(){const r=new WeightedReservoir428();r.sample=this.sample;r.weightSum=this.weightSum;r.m=this.m;r.selectedWeight=this.selectedWeight;r.source=this.source;r.age=this.age;return r;}}
class SpatialReuse429{constructor(opts={}){this.radius=opts.radius||1;this.maxNeighbors=opts.maxNeighbors||8;this.accepted=0;this.rejected=0;}reuse(grid,w,h,x,y,compat){const out=new WeightedReservoir428(),c=grid[y*w+x];if(c)out.merge(c,1);let used=0;for(let dy=-this.radius;dy<=this.radius&&used<this.maxNeighbors;dy++)for(let dx=-this.radius;dx<=this.radius&&used<this.maxNeighbors;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const r=grid[ny*w+nx];if(!r)continue;const s=compat?clamp(compat(x,y,nx,ny),0,1):1;if(s>0){out.merge(r,s);this.accepted++;}else this.rejected++;used++;}return out;}stats(){const n=this.accepted+this.rejected;return{version:'4.29.0',accepted:this.accepted,rejected:this.rejected,acceptRate:n?this.accepted/n:0};}}
class TemporalReuse430{constructor(w,h){this.w=w;this.h=h;this.prev=new Array(w*h);this.curr=new Array(w*h);this.frames=0;this.accepted=0;this.rejected=0;}begin(){this.curr=new Array(this.w*this.h);}combine(i,current,historyOk=true){const p=this.prev[i];if(p&&historyOk){current.merge(p,1);this.accepted++;}else if(p)this.rejected++;this.curr[i]=current;return current;}end(){this.prev=this.curr;this.frames++;}stats(){const q=this.accepted+this.rejected;return{version:'4.30.0',frames:this.frames,accepted:this.accepted,rejected:this.rejected,acceptRate:q?this.accepted/q:0};}}
class LitePixCore5Production431{constructor(w,h,opts={}){this.w=w;this.h=h;this.current=new Array(w*h);this.spatial=new SpatialReuse429(opts);this.temporal=new TemporalReuse430(w,h);this.shadow=new C5.ShadowReuseCache({maxEntries:opts.shadowEntries||32768});this.records=0;this.reused=0;this.started=performance.now();this.temporal.begin();}record(index,sample){const r=new WeightedReservoir428(),L=sample?.radiance||[0,0,0];r.updateTagged({radiance:L,index},Math.max(1e-8,lum(L)),'current',()=>0);this.current[index]=r;this.records++;return r;}completePass(guide){for(let i=0;i<this.current.length;i++){const r=this.current[i];if(!r)continue;const x=i%this.w,y=(i/this.w)|0,compat=guide?.compatible?((a,b,c,d)=>guide.compatible(a,b,c,d)):null,s=this.spatial.reuse(this.current,this.w,this.h,x,y,compat),h=this.temporal.combine(i,s,true);if(h.m>r.m)this.reused++;}this.temporal.end();this.temporal.begin();return this.snapshot();}snapshot(){return{version:'4.31.0',provider:'LitePix Core5 production ray reuse',architecture:'weighted reservoirs + spatial reuse + temporal reuse + shadow visibility cache',records:this.records,reused:this.reused,spatial:this.spatial.stats(),temporal:this.temporal.stats(),shadow:this.shadow.stats(),elapsedMs:performance.now()-this.started};}}
LP.Core5Production431=LitePixCore5Production431;LP.Core5.version='4.31.0';root.LitePixCore5Production431=LitePixCore5Production431;root.__LitePixCore5Reservoir428=true;root.__LitePixCore5Spatial429=true;root.__LitePixCore5Temporal430=true;root.__LitePixCore5Production431=true;
})(typeof globalThis!=='undefined'?globalThis:window);