(function(root){'use strict';
const now=()=>root.performance?.now?.()??Date.now();
const A=root.LitePixCore2PathAcceleration412;
if(typeof A!=='function')throw new Error('LitePix v4.13 requires Core2 v4.12 acceleration');
const ident=()=>[1,0,0,0,1,0,0,0,1,0,0,0];
function invAffine(m){const a=m[0],b=m[1],c=m[2],d=m[3],e=m[4],f=m[5],g=m[6],h=m[7],i=m[8],tx=m[9],ty=m[10],tz=m[11];const A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,H=b*g-a*h,I=a*e-b*d,det=a*A+b*D+c*G;if(Math.abs(det)<1e-15)throw new Error('LitePix v4.13 singular instance transform');const q=1/det,r=[A*q,B*q,C*q,D*q,E*q,F*q,G*q,H*q,I*q,0,0,0];r[9]=-(r[0]*tx+r[1]*ty+r[2]*tz);r[10]=-(r[3]*tx+r[4]*ty+r[5]*tz);r[11]=-(r[6]*tx+r[7]*ty+r[8]*tz);return r;}
const pt=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2]+m[9],m[3]*p[0]+m[4]*p[1]+m[5]*p[2]+m[10],m[6]*p[0]+m[7]*p[1]+m[8]*p[2]+m[11]];
const vec=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2],m[3]*p[0]+m[4]*p[1]+m[5]*p[2],m[6]*p[0]+m[7]*p[1]+m[8]*p[2]];
function boundsOf(acc,m){let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];if(!acc.nodeCount)return{min:[0,0,0],max:[0,0,0]};const a=[acc.nMinX[0],acc.nMinY[0],acc.nMinZ[0]],b=[acc.nMaxX[0],acc.nMaxY[0],acc.nMaxZ[0]];for(let x=0;x<2;x++)for(let y=0;y<2;y++)for(let z=0;z<2;z++){const p=pt(m,[x?b[0]:a[0],y?b[1]:a[1],z?b[2]:a[2]]);for(let k=0;k<3;k++){if(p[k]<mn[k])mn[k]=p[k];if(p[k]>mx[k])mx[k]=p[k];}}return{min:mn,max:mx};}
class LitePixBLAS413{constructor(base,job,key='mesh'){this.key=key;this.acceleration=A.wrap(base,job);this.buildMs=this.acceleration.buildMs;this.triangles=this.acceleration.triangleCount;}trace(r){return this.acceleration.trace(r)}occluded(r){return this.acceleration.occluded(r)}}
class LitePixTLAS413{
 constructor(instances=[]){this.instances=[];this.refitCount=0;this.rebuildCount=0;this.traceRays=0;this.shadowRays=0;this.nodeTests=0;this.instanceTests=0;this.buildMs=0;for(const x of instances)this.addInstance(x.blas,x.transform,x.id);this.rebuild();}
 addInstance(blas,transform=ident(),id=this.instances.length){const m=transform.slice(0,12),inv=invAffine(m);this.instances.push({id,blas,transform:m,inverse:inv,bounds:boundsOf(blas.acceleration,m)});return this.instances.length-1;}
 updateTransform(index,transform){const x=this.instances[index];if(!x)throw new Error('LitePix v4.13 instance not found');x.transform=transform.slice(0,12);x.inverse=invAffine(x.transform);x.bounds=boundsOf(x.blas.acceleration,x.transform);return this;}
 _buildNodes(){const ids=this.instances.map((_,i)=>i),nodes=[];const build=(arr)=>{let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of arr){const b=this.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}const ni=nodes.length,n={min:mn,max:mx,left:-1,right:-1,ids:null};nodes.push(n);if(arr.length<=4){n.ids=arr;return ni;}let axis=0,span=mx[0]-mn[0];for(let k=1;k<3;k++){const s=mx[k]-mn[k];if(s>span){span=s;axis=k;}}arr.sort((u,v)=>{const a=this.instances[u].bounds,b=this.instances[v].bounds;return(a.min[axis]+a.max[axis])-(b.min[axis]+b.max[axis]);});const mid=arr.length>>1;n.left=build(arr.slice(0,mid));n.right=build(arr.slice(mid));return ni;};if(ids.length)build(ids);this.nodes=nodes;}
 rebuild(){const t=now();this._buildNodes();this.buildMs+=now()-t;this.rebuildCount++;return this;}
 refit(){const t=now();for(let i=this.nodes.length-1;i>=0;i--){const n=this.nodes[i];if(n.ids){let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of n.ids){const b=this.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}n.min=mn;n.max=mx;}else{const a=this.nodes[n.left],b=this.nodes[n.right];n.min=[Math.min(a.min[0],b.min[0]),Math.min(a.min[1],b.min[1]),Math.min(a.min[2],b.min[2])];n.max=[Math.max(a.max[0],b.max[0]),Math.max(a.max[1],b.max[1]),Math.max(a.max[2],b.max[2])];}}this.refitCount++;this.lastRefitMs=now()-t;return this;}
 _box(r,n,tmax){const o=r.origin,d=r.direction;let lo=r.tMin??1e-5,hi=tmax;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-12){if(o[k]<n.min[k]||o[k]>n.max[k])return false;}else{let a=(n.min[k]-o[k])/d[k],b=(n.max[k]-o[k])/d[k];if(a>b){const q=a;a=b;b=q;}lo=Math.max(lo,a);hi=Math.min(hi,b);if(hi<lo)return false;}}return true;}
 _localRay(r,x){return{origin:pt(x.inverse,r.origin),direction:vec(x.inverse,r.direction),tMin:r.tMin,tMax:r.tMax};}
 trace(ray){this.traceRays++;if(!this.nodes.length)return{hit:false,t:Infinity};let best=null,bestT=ray.tMax??Infinity,stack=[0];while(stack.length){const ni=stack.pop(),n=this.nodes[ni];this.nodeTests++;if(!this._box(ray,n,bestT))continue;if(n.ids){for(const id of n.ids){this.instanceTests++;const x=this.instances[id],h=x.blas.trace(this._localRay({...ray,tMax:bestT},x));if(h.hit){const wp=pt(x.transform,h.position),dx=wp[0]-ray.origin[0],dy=wp[1]-ray.origin[1],dz=wp[2]-ray.origin[2],den=ray.direction[0]**2+ray.direction[1]**2+ray.direction[2]**2,wt=(dx*ray.direction[0]+dy*ray.direction[1]+dz*ray.direction[2])/den;if(wt<bestT){bestT=wt;best={...h,t:wt,position:wp,instanceId:x.id};}}}}else{stack.push(n.left,n.right);}}return best||{hit:false,t:Infinity};}
 occluded(ray){this.shadowRays++;if(!this.nodes.length)return false;const stack=[0],tm=ray.tMax??Infinity;while(stack.length){const n=this.nodes[stack.pop()];this.nodeTests++;if(!this._box(ray,n,tm))continue;if(n.ids){for(const id of n.ids){this.instanceTests++;const x=this.instances[id];if(x.blas.occluded(this._localRay(ray,x)))return true;}}else stack.push(n.left,n.right);}return false;}
 snapshot(){return{version:'4.13.0',provider:'LitePix Core2 BLAS/TLAS',instances:this.instances.length,uniqueBLAS:new Set(this.instances.map(x=>x.blas)).size,tlasNodes:this.nodes.length,rebuildCount:this.rebuildCount,refitCount:this.refitCount,lastRefitMs:+(this.lastRefitMs||0).toFixed(3),traceRays:this.traceRays,shadowRays:this.shadowRays,nodeTests:this.nodeTests,instanceTests:this.instanceTests};}
}
root.LitePixBLAS413=LitePixBLAS413;root.LitePixTLAS413=LitePixTLAS413;root.__LitePixCore2BLASTLAS413=true;
})(typeof globalThis!=='undefined'?globalThis:window);