(function(root){'use strict';
const LP=root.LitePixNative=root.LitePixNative||{};
const C4=LP.Core4;if(!C4)throw new Error('LitePix Core4 base missing');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),now=()=>root.performance?.now?.()??Date.now();
const l3n=(name,...args)=>{try{const f=root[name];if(typeof f==='function')return f(...args);}catch(_){}return undefined;};
class IrradianceCache424{constructor(opts={}){this.cache=new C4.RadianceCache({cellSize:opts.cellSize||24,normalThreshold:opts.normalThreshold??.75,distanceScale:opts.distanceScale??1.25});this.inserts=0;this.updates=0;this.queries=0;}query(p,n){this.queries++;l3n('__3DLiteL3NCache','lightCache','lookup',1);const q=this.cache.query(p,n);l3n('__3DLiteL3NCache','lightCache',q?'hit':'miss',1);return q;}insert(p,n,L,radius=32,variance=1,confidence=.25){this.inserts++;return this.cache.add(new C4.RadianceRecord(p,n,L,radius,variance,confidence));}update(i,L,v,c){if(this.cache.update(i,L,v,c)){this.updates++;return true;}return false;}stats(){return{version:'4.48.0',...this.cache.stats(),inserts:this.inserts,updates:this.updates,queries:this.queries};}}
class ProbeHierarchy425{constructor(opts={}){this.levels=opts.levels||4;this.baseResolution=opts.baseResolution||8;this.probes=[];this.refinements=0;}add(p,n,level=0){const res=Math.min(64,this.baseResolution<<Math.min(level,this.levels-1)),probe={p:p.slice(),n:n.slice(),level,resolution:res,radiance:new Float32Array(res*res*3),samples:0,variance:1,confidence:0};this.probes.push(probe);return probe;}refine(probe){if(!probe||probe.level>=this.levels-1)return probe;probe.level++;probe.resolution=Math.min(64,this.baseResolution<<probe.level);probe.radiance=new Float32Array(probe.resolution*probe.resolution*3);probe.samples=0;this.refinements++;return probe;}stats(){return{version:'4.48.0',probes:this.probes.length,refinements:this.refinements,levels:this.levels};}}
class AdaptiveGI426{constructor(w,h,opts={}){this.hgi=new C4.HierarchicalGI(w,h,{startBlock:opts.startBlock||32,minBlock:opts.minBlock||1,maxLevel:opts.maxLevel||7,varianceThreshold:opts.varianceThreshold??.018,errorThreshold:opts.errorThreshold??.025});this.samples=0;this.passes=0;this.totalMs=0;}run(accumulator,guide){const t=now(),w=this.hgi.width,h=this.hgi.height;const sample=b=>{const x=Math.min(w-1,b.x+(b.size>>1)),y=Math.min(h-1,b.y+(b.size>>1)),i=y*w+x,o=i*3,s=Math.max(1,accumulator.samples[i]);this.samples++;return{radiance:[accumulator.sum[o]/s,accumulator.sum[o+1]/s,accumulator.sum[o+2]/s],variance:Number.isFinite(accumulator.variance(i))?accumulator.variance(i):1,error:Number.isFinite(accumulator.noise(i))?accumulator.noise(i):1,confidence:clamp(s/8,0,1)};};const imp=b=>{if(!guide?.importance)return 0;const x=Math.min(w-1,b.x+(b.size>>1)),y=Math.min(h-1,b.y+(b.size>>1));return guide.importance(x,y);};l3n('__3DLiteL3NBeginStage','adaptive-gi',{source:'Core4Production',pass:this.passes+1});if(this.hgi.active.length)this.hgi.runPass(sample,imp);this.passes++;const ms=now()-t;this.totalMs+=ms;l3n('__3DLiteL3NEndStage','adaptive-gi',{source:'Core4Production',pass:this.passes});l3n('__3DLiteL3NObserveStage','adaptive-gi-pass',ms,{source:'Core4Production',samples:this.samples});return this.stats();}stats(){return{version:'4.48.0',passes:this.passes,samples:this.samples,totalMs:this.totalMs,...this.hgi.stats()};}}
class LitePixCore4Production427{constructor(w,h,opts={}){this.cache=new IrradianceCache424(opts);this.probes=new ProbeHierarchy425(opts);this.adaptive=new AdaptiveGI426(w,h,opts);this.primaryHits=0;this.cacheHits=0;this.cacheMisses=0;this.inserts=0;this.started=now();}recordPrimary(hit,sample,accumulator,index){if(!hit?.hit)return;this.primaryHits++;const p=hit.position||[0,0,0],n=hit.orientedGeometricNormal||hit.geometricNormal||[0,1,0],q=this.cache.query(p,n);if(q)this.cacheHits++;else{this.cacheMisses++;const L=sample?.radiance||[0,0,0],v=accumulator&&accumulator.samples[index]>1?accumulator.variance(index):1,c=accumulator?clamp(accumulator.samples[index]/8,0,1):.1;this.cache.insert(p,n,L,Math.max(8,Math.sqrt(Math.abs(hit.t||1))*12),v,c);this.inserts++;}if((this.primaryHits&255)===0)l3n('__3DLiteL3NColor','raw',sample?.radiance||[0,0,0]);}completePass(accumulator,guide){return this.adaptive.run(accumulator,guide);}snapshot(){const c=this.cache.stats(),snap={version:'4.48.0',provider:'LitePix Core4 production hierarchical GI + L3N evidence',architecture:'irradiance cache + probe hierarchy + adaptive hierarchical GI',primaryHits:this.primaryHits,cacheHits:this.cacheHits,cacheMisses:this.cacheMisses,inserts:this.inserts,cache:c,probes:this.probes.stats(),adaptive:this.adaptive.stats(),elapsedMs:now()-this.started};l3n('__3DLiteL3NLearn','light-cache-effectiveness','cache reuse should reduce GI cost without blocking convergence',`hitRate ${Number(c.hitRate||0).toFixed(4)} hits ${c.hits||0} misses ${c.misses||0}`,'OBSERVED',(c.hits+c.misses)>100?'HIGH':'LOW');return snap;}}
LP.Core4Production427=LitePixCore4Production427;LP.Core4.version='4.48.0';root.LitePixCore4Production427=LitePixCore4Production427;root.__LitePixCore4GI424=true;root.__LitePixCore4Probe425=true;root.__LitePixCore4Adaptive426=true;root.__LitePixCore4Production427=true;root.__LitePixCore4L3N448=true;
})(typeof globalThis!=='undefined'?globalThis:window);
