(function(root){'use strict';
const Sel=root.LitePixCore2TLASAcceleration416;
if(typeof Sel!=='function')throw new Error('LitePix v4.17 requires Core2 v4.16');
function boxEntry(ray,min,max,tMax){const o=ray.origin,d=ray.direction;let lo=ray.tMin??1e-5,hi=tMax;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-12){if(o[k]<min[k]||o[k]>max[k])return Infinity;}else{let a=(min[k]-o[k])/d[k],b=(max[k]-o[k])/d[k];if(a>b){const q=a;a=b;b=q;}lo=Math.max(lo,a);hi=Math.min(hi,b);if(hi<lo)return Infinity;}}return lo;}
function buildTree(inner,ids){const nodes=[];const rec=arr=>{let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of arr){const b=inner.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}const ni=nodes.length,n={min:mn,max:mx,left:-1,right:-1,ids:null};nodes.push(n);if(arr.length<=4){n.ids=arr.slice();return ni;}let ax=0,sp=mx[0]-mn[0];for(let k=1;k<3;k++){const q=mx[k]-mn[k];if(q>sp){sp=q;ax=k;}}arr.sort((a,b)=>{const A=inner.instances[a].bounds,B=inner.instances[b].bounds;return(A.min[ax]+A.max[ax])-(B.min[ax]+B.max[ax]);});const m=arr.length>>1;n.left=rec(arr.slice(0,m));n.right=rec(arr.slice(m));return ni;};if(ids.length)rec(ids.slice());return nodes;}
class StaticDynamicCache417{
 constructor(){this.dynamicIds=new Set();this.innerIdentity=null;this.staticNodes=[];this.dynamicNodes=[];this.splitBuilds=0;this.dynamicRebuilds=0;this.staticRebuilds=0;this.lastDirty=[];}
 reset(){this.dynamicIds.clear();this.innerIdentity=null;this.staticNodes=[];this.dynamicNodes=[];}
 prepare(base,job){const a=Sel.wrap(base,job),inner=a.inner,scene=job?.renderScene,dirty=a.cache?.lastDirty||[];for(const i of dirty){const id=String(scene?.objects?.[i]?.id??i);this.dynamicIds.add(id);}for(let i=0;i<(scene?.objects?.length||0);i++){const o=scene.objects[i];if(o?.dynamic===true||o?.isDynamic===true||o?.motionType==='dynamic')this.dynamicIds.add(String(o.id??i));}
 const staticIdx=[],dynamicIdx=[];for(let i=0;i<inner.instances.length;i++){const x=inner.instances[i],id=String(scene?.objects?.[x.objectIndex]?.id??x.id??x.objectIndex);(this.dynamicIds.has(id)?dynamicIdx:staticIdx).push(i);}const identity=inner.instances.map(x=>String(x.id)).join('|'),classification=dynamicIdx.join(',');const prevClass=this._classification;
 if(this.innerIdentity!==identity||prevClass!==classification){this.staticNodes=buildTree(inner,staticIdx);this.dynamicNodes=buildTree(inner,dynamicIdx);this.staticRebuilds++;this.dynamicRebuilds++;this.splitBuilds++;this.innerIdentity=identity;this._classification=classification;}else if(dirty.length){this.dynamicNodes=buildTree(inner,dynamicIdx);this.dynamicRebuilds++;}
 this.lastDirty=dirty.slice();const out=new StaticDynamicAcceleration417(inner,a,this,staticIdx,dynamicIdx);job.litePixCore2Dynamic417=out;return out;}
 snapshot(){return{version:'4.17.0',provider:'LitePix Core2 static/dynamic split',dynamicIds:[...this.dynamicIds],staticInstances:this._staticCount||0,dynamicInstances:this._dynamicCount||0,splitBuilds:this.splitBuilds,staticRebuilds:this.staticRebuilds,dynamicRebuilds:this.dynamicRebuilds,lastDirty:this.lastDirty};}
}
class StaticDynamicAcceleration417{
 constructor(inner,source,cache,staticIdx,dynamicIdx){this.inner=inner;this.source=source;this.base=source.base;this.store=source.store;this.job=source.job;this.cache=cache;cache._staticCount=staticIdx.length;cache._dynamicCount=dynamicIdx.length;this.traceRays=0;this.shadowRays=0;}
 static wrap(base,job){if(base instanceof StaticDynamicAcceleration417)return base;if(job?.litePixCore2Dynamic417?.base===base)return job.litePixCore2Dynamic417;return LitePixCore2DynamicCache417.prepare(base,job);}
 _traceTree(ray,nodes,best,bestT){if(!nodes.length)return[best,bestT];const st=[0];while(st.length){const n=nodes[st.pop()];if(!Number.isFinite(boxEntry(ray,n.min,n.max,bestT)))continue;if(n.ids){for(const id of n.ids){const x=this.inner.instances[id],h=x.blas.trace(this.inner._localRay({...ray,tMax:bestT},x));if(h.hit){const w=this.inner._worldHit(ray,x,h);if(w.t<bestT){best=w;bestT=w.t;}}}}else st.push(n.left,n.right);}return[best,bestT];}
 trace(ray){this.traceRays++;let best=null,t=ray.tMax??Infinity;[best,t]=this._traceTree(ray,this.cache.staticNodes,best,t);[best,t]=this._traceTree(ray,this.cache.dynamicNodes,best,t);return best||{hit:false,t:Infinity,u:0,v:0,objectIndex:-1,triangleIndex:-1,position:null,geometricNormal:null,orientedGeometricNormal:null,frontFace:true,materialIndex:0};}
 _occTree(ray,nodes){if(!nodes.length)return false;const st=[0],tm=ray.tMax??Infinity;while(st.length){const n=nodes[st.pop()];if(!Number.isFinite(boxEntry(ray,n.min,n.max,tm)))continue;if(n.ids){for(const id of n.ids){const x=this.inner.instances[id];if(x.blas.occluded(this.inner._localRay(ray,x)))return true;}}else st.push(n.left,n.right);}return false;}
 occluded(ray){this.shadowRays++;return this._occTree(ray,this.cache.staticNodes)||this._occTree(ray,this.cache.dynamicNodes);}
 snapshot(){return{...(this.source.snapshot?.()||{}),...this.cache.snapshot(),traceRays417:this.traceRays,shadowRays417:this.shadowRays};}
}
const LitePixCore2DynamicCache417=new StaticDynamicCache417();
root.LitePixCore2DynamicCache417=LitePixCore2DynamicCache417;root.LitePixCore2DynamicAcceleration417=StaticDynamicAcceleration417;root.__LitePixCore2Dynamic417=true;
})(typeof globalThis!=='undefined'?globalThis:window);