(function(root){'use strict';
const LP=root.LitePixNative=root.LitePixNative||{};
let sharedTemporal=null;
function id32(v){if(Number.isInteger(v))return v>>>0;const s=String(v??'');let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0;}return h;}
class LitePixCore3Production423{
  constructor(width,height,opts={}){const G=LP.Core3ProductionGBuffer420?.ProductionGBuffer420||root.LitePixProductionGBuffer420,P=LP.Core3GuidePyramid421?.GuidePyramid421||root.LitePixGuidePyramid421,T=LP.Core3Temporal422?.TemporalGuide422||root.LitePixTemporalGuide422;if(!G||!P||!T)throw new Error('LitePix Core3 v4.23 requires v4.20-v4.22');this.width=width|0;this.height=height|0;this.gbuffer=new G(this.width,this.height);this.Pyramid=P;this.opts=opts;this.pyramid=null;if(!sharedTemporal||sharedTemporal.width!==this.width||sharedTemporal.height!==this.height)sharedTemporal=new T(this.width,this.height,opts.temporal||{});this.temporal=sharedTemporal;this.frame=0;this.records=0;this.primaryHits=0;this.misses=0;this.passes=0;this.edgeMean=0;this.temporalTests=0;this.startedAt=performance.now();}
  beginFrame(){this.frame++;this.records=0;this.primaryHits=0;this.misses=0;this.passes=0;this.edgeMean=0;this.temporalTests=0;this.gbuffer.beginFrame();this.temporal.beginFrame();return this;}
  recordPrimary(index,x,y,ray,sample,hit,job,compiled,acceleration){this.records++;if(!hit?.hit){this.gbuffer.invalidate(index);this.misses++;return;}this.primaryHits++;const mod=LP.Core3ProductionGBuffer420,ms=mod?.materialSnapshot?mod.materialSnapshot(job,hit):{albedo:[.5,.5,.5],emissive:[0,0,0],roughness:.5,metallic:0,opacity:1};let sn=hit.orientedGeometricNormal||hit.geometricNormal||[0,1,0];try{if(root.SurfaceInterpolator?.normal)sn=root.SurfaceInterpolator.normal(acceleration,hit)||sn;}catch(_){}const gn=hit.orientedGeometricNormal||hit.geometricNormal||sn,p=hit.position||[0,0,0];this.gbuffer.write(index,{depth:Number(hit.t??hit.distance??Infinity),position:p,geometricNormal:gn,shadingNormal:sn,albedo:ms.albedo,emissive:ms.emissive,roughness:ms.roughness,metallic:ms.metallic,opacity:ms.opacity,materialId:id32(hit.materialIndex??0),objectId:id32(hit.objectIndex??hit.objectId??0),triangleId:id32(hit.triangleIndex??hit.triangleId??0),motion:[0,0]});}
  completePass(){this.passes++;this.pyramid=new this.Pyramid(this.gbuffer);const L=this.pyramid.levels[0];let sum=0,count=0;for(let i=0;i<L.edge.length;i++)if(L.valid[i]){sum+=L.edge[i];count++;}this.edgeMean=count?sum/count:0;if(this.temporal.history){const step=Math.max(1,Math.floor(this.gbuffer.valid.length/2048));for(let i=0;i<this.gbuffer.valid.length;i+=step){if(!this.gbuffer.valid[i])continue;this.temporal.validate(this.gbuffer,i);this.temporalTests++;}}return this.snapshot();}
  endFrame(){if(!this.pyramid)this.completePass();this.temporal.commit(this.gbuffer);return this.snapshot();}
  snapshot(){return{version:'4.23.0',provider:'LitePix Core3 production raster guide',architecture:'production G-buffer + hierarchical guide pyramid + temporal reprojection/disocclusion validation',frame:this.frame,records:this.records,primaryHits:this.primaryHits,misses:this.misses,passes:this.passes,edgeMean:this.edgeMean,temporalTests:this.temporalTests,gbuffer:this.gbuffer.snapshot(),pyramid:this.pyramid?.snapshot?.()||null,temporal:this.temporal.snapshot(),elapsedMs:performance.now()-this.startedAt};}
}
LP.Core3Production423=LitePixCore3Production423;LP.Core3={...(LP.Core3||{}),ProductionGBuffer420:LP.Core3ProductionGBuffer420?.ProductionGBuffer420,GuidePyramid421:LP.Core3GuidePyramid421?.GuidePyramid421,TemporalGuide422:LP.Core3Temporal422?.TemporalGuide422,Production423:LitePixCore3Production423,version:'4.23.0'};
root.LitePixCore3Production423=LitePixCore3Production423;root.__LitePixCore3Production423=true;root.__LitePixCore3Production423Enabled=true;
})(typeof globalThis!=='undefined'?globalThis:window);
