(function(root){'use strict';
const now=()=>root.performance?.now?.()??Date.now();
const Core2=root.LitePixNative?.Core2;
if(!Core2||typeof Core2.SAHBVH!=='function')throw new Error('LitePix v4.13 requires Core2 SAHBVH');
const miss=()=>({hit:false,t:Infinity,u:0,v:0,objectIndex:-1,triangleIndex:-1,position:null,geometricNormal:null,orientedGeometricNormal:null,frontFace:true,materialIndex:0});
const pt=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2]+m[9],m[3]*p[0]+m[4]*p[1]+m[5]*p[2]+m[10],m[6]*p[0]+m[7]*p[1]+m[8]*p[2]+m[11]];
const vec=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2],m[3]*p[0]+m[4]*p[1]+m[5]*p[2],m[6]*p[0]+m[7]*p[1]+m[8]*p[2]];
function invAffine(m){const a=m[0],b=m[1],c=m[2],d=m[3],e=m[4],f=m[5],g=m[6],h=m[7],i=m[8],tx=m[9],ty=m[10],tz=m[11];const A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,H=b*g-a*h,I=a*e-b*d,det=a*A+b*D+c*G;if(Math.abs(det)<1e-15)throw new Error('LitePix v4.13 singular transform');const q=1/det,r=[A*q,B*q,C*q,D*q,E*q,F*q,G*q,H*q,I*q,0,0,0];r[9]=-(r[0]*tx+r[1]*ty+r[2]*tz);r[10]=-(r[3]*tx+r[4]*ty+r[5]*tz);r[11]=-(r[6]*tx+r[7]*ty+r[8]*tz);return r;}
function nrmWorld(inv,n){let x=inv[0]*n[0]+inv[3]*n[1]+inv[6]*n[2],y=inv[1]*n[0]+inv[4]*n[1]+inv[7]*n[2],z=inv[2]*n[0]+inv[5]*n[1]+inv[8]*n[2],l=Math.hypot(x,y,z)||1;return[x/l,y/l,z/l];}
function boxEntry(ray,min,max,tMax){const o=ray.origin,d=ray.direction;let lo=ray.tMin??1e-5,hi=tMax;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-12){if(o[k]<min[k]||o[k]>max[k])return Infinity;}else{let a=(min[k]-o[k])/d[k],b=(max[k]-o[k])/d[k];if(a>b){const q=a;a=b;b=q;}if(a>lo)lo=a;if(b<hi)hi=b;if(hi<lo)return Infinity;}}return lo;}
class LitePixLocalBLAS413{
 constructor(mesh,key){this.key=key;this.mesh=mesh;this.triangleCount=mesh.indices.length/3;this._pack();const primitives=new Array(this.triangleCount);for(let t=0;t<this.triangleCount;t++){const k=t*3,ia=this.idx[k]*3,ib=this.idx[k+1]*3,ic=this.idx[k+2]*3;const min=[Math.min(this.pos[ia],this.pos[ib],this.pos[ic]),Math.min(this.pos[ia+1],this.pos[ib+1],this.pos[ic+1]),Math.min(this.pos[ia+2],this.pos[ib+2],this.pos[ic+2])],max=[Math.max(this.pos[ia],this.pos[ib],this.pos[ic]),Math.max(this.pos[ia+1],this.pos[ib+1],this.pos[ic+1]),Math.max(this.pos[ia+2],this.pos[ib+2],this.pos[ic+2])];primitives[t]={bounds:{min,max},triangleIndex:t};}const t0=now();this.bvh=new Core2.SAHBVH({maxLeaf:4,bins:24}).build(primitives);this.buildMs=now()-t0;this.rootBounds=this.bvh.nodes.length?this.bvh.nodes[0].bounds:{min:[0,0,0],max:[0,0,0]};}
 _pack(){this.pos=this.mesh.positions;this.norm=this.mesh.normals;this.uvs=this.mesh.uvs;this.idx=this.mesh.indices;this.mat=this.mesh.materialIndices;}
 _tri(t,ray,tMax){const k=t*3,ia=this.idx[k]*3,ib=this.idx[k+1]*3,ic=this.idx[k+2]*3,p=this.pos;const ax=p[ia],ay=p[ia+1],az=p[ia+2],e1x=p[ib]-ax,e1y=p[ib+1]-ay,e1z=p[ib+2]-az,e2x=p[ic]-ax,e2y=p[ic+1]-ay,e2z=p[ic+2]-az,dx=ray.direction[0],dy=ray.direction[1],dz=ray.direction[2],pvx=dy*e2z-dz*e2y,pvy=dz*e2x-dx*e2z,pvz=dx*e2y-dy*e2x,det=e1x*pvx+e1y*pvy+e1z*pvz;if(Math.abs(det)<1e-12)return null;const inv=1/det,tvx=ray.origin[0]-ax,tvy=ray.origin[1]-ay,tvz=ray.origin[2]-az,u=(tvx*pvx+tvy*pvy+tvz*pvz)*inv;if(u<0||u>1)return null;const qx=tvy*e1z-tvz*e1y,qy=tvz*e1x-tvx*e1z,qz=tvx*e1y-tvy*e1x,v=(dx*qx+dy*qy+dz*qz)*inv;if(v<0||u+v>1)return null;const ht=(e2x*qx+e2y*qy+e2z*qz)*inv;if(ht<(ray.tMin??1e-5)||ht>tMax)return null;let nx=e1y*e2z-e1z*e2y,ny=e1z*e2x-e1x*e2z,nz=e1x*e2y-e1y*e2x,l=Math.hypot(nx,ny,nz)||1;nx/=l;ny/=l;nz/=l;const w=1-u-v;let sn=[nx,ny,nz];if(this.norm?.length===this.pos.length){const na=this.idx[k]*3,nb=this.idx[k+1]*3,nc=this.idx[k+2]*3;sn=[this.norm[na]*w+this.norm[nb]*u+this.norm[nc]*v,this.norm[na+1]*w+this.norm[nb+1]*u+this.norm[nc+1]*v,this.norm[na+2]*w+this.norm[nb+2]*u+this.norm[nc+2]*v];l=Math.hypot(...sn)||1;sn=sn.map(x=>x/l);}let uv=[0,0];if(this.uvs?.length===(this.pos.length/3)*2){const a=this.idx[k]*2,b=this.idx[k+1]*2,c=this.idx[k+2]*2;uv=[this.uvs[a]*w+this.uvs[b]*u+this.uvs[c]*v,this.uvs[a+1]*w+this.uvs[b+1]*u+this.uvs[c+1]*v];}return{hit:true,t:ht,u,v,triangleIndex:t,position:[ray.origin[0]+dx*ht,ray.origin[1]+dy*ht,ray.origin[2]+dz*ht],geometricNormal:[nx,ny,nz],shadingNormal:sn,uv,materialIndex:this.mat?.[t]??0};}
 trace(ray){if(!this.bvh.nodes.length)return miss();let best=null,bestT=ray.tMax??Infinity,stack=[0];while(stack.length){const ni=stack.pop(),n=this.bvh.nodes[ni];if(!Number.isFinite(boxEntry(ray,n.bounds.min,n.bounds.max,bestT)))continue;if(n.leaf){for(let i=n.start;i<n.start+n.count;i++){const t=this.bvh.primitives[this.bvh.indices[i]].triangleIndex,h=this._tri(t,ray,bestT);if(h){best=h;bestT=h.t;}}}else{const l=this.bvh.nodes[n.left],r=this.bvh.nodes[n.right],le=boxEntry(ray,l.bounds.min,l.bounds.max,bestT),re=boxEntry(ray,r.bounds.min,r.bounds.max,bestT);if(le<re){if(Number.isFinite(re))stack.push(n.right);if(Number.isFinite(le))stack.push(n.left);}else{if(Number.isFinite(le))stack.push(n.left);if(Number.isFinite(re))stack.push(n.right);}}}return best||miss();}
 occluded(ray){if(!this.bvh.nodes.length)return false;const tm=ray.tMax??Infinity,stack=[0];while(stack.length){const n=this.bvh.nodes[stack.pop()];if(!Number.isFinite(boxEntry(ray,n.bounds.min,n.bounds.max,tm)))continue;if(n.leaf){for(let i=n.start;i<n.start+n.count;i++){const t=this.bvh.primitives[this.bvh.indices[i]].triangleIndex;if(this._tri(t,ray,tm))return true;}}else stack.push(n.left,n.right);}return false;}
}
class LitePixSceneAcceleration413{
 constructor(base,job){this.base=base;this.store=base?.store;this.job=job;this.instances=[];this.blasByKey=new Map();this.traceRays=0;this.shadowRays=0;this.refitCount=0;this.rebuildCount=0;this._build(job?.renderScene);}
 static wrap(base,job){if(base instanceof LitePixSceneAcceleration413)return base;if(job?.litePixCore2Scene413?.base===base)return job.litePixCore2Scene413;const a=new LitePixSceneAcceleration413(base,job);if(job)job.litePixCore2Scene413=a;return a;}
 _build(scene){const t0=now();if(!scene?.objects?.length){this.fallback=true;this.buildMs=0;return;}for(let objectIndex=0;objectIndex<scene.objects.length;objectIndex++){const o=scene.objects[objectIndex];if(!o.localMesh||!o.transform||!o.geometryId){this.fallback=true;this.buildMs=0;return;}let blas=this.blasByKey.get(o.geometryId);if(!blas){blas=new LitePixLocalBLAS413(o.localMesh,o.geometryId);this.blasByKey.set(o.geometryId,blas);}const m=Array.from(o.transform),inv=invAffine(m),b=blas.rootBounds;let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let x=0;x<2;x++)for(let y=0;y<2;y++)for(let z=0;z<2;z++){const p=pt(m,[x?b.max[0]:b.min[0],y?b.max[1]:b.min[1],z?b.max[2]:b.min[2]]);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[k]);mx[k]=Math.max(mx[k],p[k]);}}this.instances.push({id:o.id,objectIndex,blas,transform:m,inverse:inv,bounds:{min:mn,max:mx}});}this._buildTLAS();this.buildMs=now()-t0;}
 _buildTLAS(){const ids=this.instances.map((_,i)=>i),nodes=[];const build=(arr)=>{let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of arr){const b=this.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}const ni=nodes.length,n={min:mn,max:mx,left:-1,right:-1,ids:null};nodes.push(n);if(arr.length<=4){n.ids=arr;return ni;}let ax=0,sp=mx[0]-mn[0];for(let k=1;k<3;k++){const q=mx[k]-mn[k];if(q>sp){sp=q;ax=k;}}arr.sort((a,b)=>{const A=this.instances[a].bounds,B=this.instances[b].bounds;return(A.min[ax]+A.max[ax])-(B.min[ax]+B.max[ax]);});const mid=arr.length>>1;n.left=build(arr.slice(0,mid));n.right=build(arr.slice(mid));return ni;};if(ids.length)build(ids);this.nodes=nodes;this.rebuildCount++;}
 _localRay(ray,x){return{origin:pt(x.inverse,ray.origin),direction:vec(x.inverse,ray.direction),tMin:ray.tMin,tMax:ray.tMax};}
 _worldHit(ray,x,h){const wp=pt(x.transform,h.position),gn=nrmWorld(x.inverse,h.geometricNormal),sn=nrmWorld(x.inverse,h.shadingNormal||h.geometricNormal),front=(ray.direction[0]*gn[0]+ray.direction[1]*gn[1]+ray.direction[2]*gn[2])<0,ogn=front?gn:[-gn[0],-gn[1],-gn[2]],aligned=(sn[0]*ogn[0]+sn[1]*ogn[1]+sn[2]*ogn[2])<0?[-sn[0],-sn[1],-sn[2]]:sn,dx=wp[0]-ray.origin[0],dy=wp[1]-ray.origin[1],dz=wp[2]-ray.origin[2],den=ray.direction[0]**2+ray.direction[1]**2+ray.direction[2]**2,wt=(dx*ray.direction[0]+dy*ray.direction[1]+dz*ray.direction[2])/den;return{...h,t:wt,position:wp,objectIndex:x.objectIndex,instanceId:x.id,geometricNormal:gn,orientedGeometricNormal:ogn,shadingNormal:aligned,frontFace:front};}
 trace(ray){if(this.fallback)return root.LitePixCore2PathAcceleration412.wrap(this.base,this.job).trace(ray);this.traceRays++;if(!this.nodes.length)return miss();let best=null,bestT=ray.tMax??Infinity,stack=[0];while(stack.length){const n=this.nodes[stack.pop()];if(!Number.isFinite(boxEntry(ray,n.min,n.max,bestT)))continue;if(n.ids){for(const id of n.ids){const x=this.instances[id],h=x.blas.trace(this._localRay({...ray,tMax:bestT},x));if(h.hit){const w=this._worldHit(ray,x,h);if(w.t<bestT){best=w;bestT=w.t;}}}}else stack.push(n.left,n.right);}return best||miss();}
 occluded(ray){if(this.fallback)return root.LitePixCore2PathAcceleration412.wrap(this.base,this.job).occluded(ray);this.shadowRays++;if(!this.nodes.length)return false;const tm=ray.tMax??Infinity,stack=[0];while(stack.length){const n=this.nodes[stack.pop()];if(!Number.isFinite(boxEntry(ray,n.min,n.max,tm)))continue;if(n.ids){for(const id of n.ids){const x=this.instances[id];if(x.blas.occluded(this._localRay(ray,x)))return true;}}else stack.push(n.left,n.right);}return false;}
 updateTransforms(scene){if(this.fallback||!scene?.objects)return false;for(const x of this.instances){const o=scene.objects[x.objectIndex];if(!o?.transform)return false;x.transform=Array.from(o.transform);x.inverse=invAffine(x.transform);const b=x.blas.rootBounds;let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let a=0;a<2;a++)for(let c=0;c<2;c++)for(let d=0;d<2;d++){const p=pt(x.transform,[a?b.max[0]:b.min[0],c?b.max[1]:b.min[1],d?b.max[2]:b.min[2]]);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[k]);mx[k]=Math.max(mx[k],p[k]);}}x.bounds={min:mn,max:mx};}for(let i=this.nodes.length-1;i>=0;i--){const n=this.nodes[i];if(n.ids){let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of n.ids){const b=this.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}n.min=mn;n.max=mx;}else{const a=this.nodes[n.left],b=this.nodes[n.right];n.min=[Math.min(a.min[0],b.min[0]),Math.min(a.min[1],b.min[1]),Math.min(a.min[2],b.min[2])];n.max=[Math.max(a.max[0],b.max[0]),Math.max(a.max[1],b.max[1]),Math.max(a.max[2],b.max[2])];}}this.refitCount++;return true;}
 snapshot(){return{version:'4.13.0',provider:this.fallback?'LitePix Core2 v4.12 fallback':'LitePix Core2 BLAS/TLAS scene acceleration',instances:this.instances.length,uniqueBLAS:this.blasByKey.size,tlasNodes:this.nodes?.length||0,buildMs:+(this.buildMs||0).toFixed(3),rebuildCount:this.rebuildCount,refitCount:this.refitCount,traceRays:this.traceRays,shadowRays:this.shadowRays,fallback:!!this.fallback};}
}
root.LitePixLocalBLAS413=LitePixLocalBLAS413;root.LitePixSceneAcceleration413=LitePixSceneAcceleration413;root.__LitePixCore2Scene413=true;
})(typeof globalThis!=='undefined'?globalThis:window);