(function(root){'use strict';
const LP=root.LitePixNative=root.LitePixNative||{};
const Core2=LP.Core2;
if(!Core2||typeof Core2.SAHBVH!=='function')throw new Error('LitePix v4.11 requires Core2 SAHBVH');
const now=()=>root.performance?.now?.()??Date.now();
const miss=()=>({hit:false,t:Infinity,u:0,v:0,objectIndex:-1,triangleIndex:-1,position:null,geometricNormal:null,orientedGeometricNormal:null,frontFace:true,materialIndex:0});
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const norm=a=>{const l=Math.hypot(a[0],a[1],a[2])||1;return[a[0]/l,a[1]/l,a[2]/l]};
function boxEntry(ray,b,tLimit){let t0=ray.tMin??1e-5,t1=Math.min(ray.tMax??Infinity,tLimit);for(let k=0;k<3;k++){const d=ray.direction[k],o=ray.origin[k];if(Math.abs(d)<1e-12){if(o<b.min[k]||o>b.max[k])return Infinity;continue;}let a=(b.min[k]-o)/d,c=(b.max[k]-o)/d;if(a>c){const q=a;a=c;c=q;}if(a>t0)t0=a;if(c<t1)t1=c;if(t1<t0)return Infinity;}return t0;}
function triHit(store,ti,ray,bestT=Infinity){const k=ti*3,ia=store.triangles[k],ib=store.triangles[k+1],ic=store.triangles[k+2];const p0=store.vertex(ia),p1=store.vertex(ib),p2=store.vertex(ic);const e1=sub(p1,p0),e2=sub(p2,p0),pv=cross(ray.direction,e2),det=dot(e1,pv);if(Math.abs(det)<1e-12)return null;const inv=1/det,tv=sub(ray.origin,p0),u=dot(tv,pv)*inv;if(u<0||u>1)return null;const qv=cross(tv,e1),v=dot(ray.direction,qv)*inv;if(v<0||u+v>1)return null;const t=dot(e2,qv)*inv;if(t<(ray.tMin??1e-5)||t>(ray.tMax??Infinity)||t>=bestT)return null;const gn=norm(cross(e1,e2)),front=dot(ray.direction,gn)<0;return{hit:true,t,u,v,objectIndex:store.objectIndices[ti]??-1,triangleIndex:ti,position:add(ray.origin,mul(ray.direction,t)),geometricNormal:gn,orientedGeometricNormal:front?gn:mul(gn,-1),frontFace:front,materialIndex:store.materialIndices[ti]??0};}
class LitePixCore2PathAcceleration411{
  constructor(base,job){this.base=base;this.store=base?.store;if(!this.store)throw new Error('LitePix Core2 path adapter requires RenderAccelerationSet.store');this.jobId=job?.id??null;this.vertexCount=base.vertexCount??this.store.positions.length/3;this.triangleCount=base.triangleCount??this.store.triangleCount();const primitives=new Array(this.triangleCount);for(let i=0;i<this.triangleCount;i++){const b=this.store.triangleBounds(i);primitives[i]={bounds:{min:b.min,max:b.max},triangleIndex:i};}const t=now();this.bvh=new Core2.SAHBVH({maxLeaf:4,bins:16}).build(primitives);this.buildMs=now()-t;this.nodeCount=this.bvh.nodes.length;this.counters={traceRays:0,shadowRays:0,nodeTests:0,triangleTests:0,hits:0,anyHits:0,traceMs:0};this.stats=Object.freeze({geometry:this.store.stats,bvh:this.bvh.stats(),provider:'LitePix Core2 SAH BVH v4.11'});}
  static wrap(base,job){if(base instanceof LitePixCore2PathAcceleration411)return base;if(job?.litePixCore2Acceleration411?.base===base)return job.litePixCore2Acceleration411;const a=new LitePixCore2PathAcceleration411(base,job);if(job)job.litePixCore2Acceleration411=a;return a;}
  trace(ray){const t0=now();this.counters.traceRays++;let best=miss();if(!this.bvh.nodes.length){this.counters.traceMs+=now()-t0;return best;}const stack=[0];while(stack.length){const ni=stack.pop(),n=this.bvh.nodes[ni];this.counters.nodeTests++;if(!Number.isFinite(boxEntry(ray,n.bounds,best.t)))continue;if(n.leaf){for(let i=n.start;i<n.start+n.count;i++){const pi=this.bvh.indices[i],ti=this.bvh.primitives[pi].triangleIndex;this.counters.triangleTests++;const h=triHit(this.store,ti,ray,best.t);if(h)best=h;}}else{const l=this.bvh.nodes[n.left],r=this.bvh.nodes[n.right],le=boxEntry(ray,l.bounds,best.t),re=boxEntry(ray,r.bounds,best.t);if(le<re){if(Number.isFinite(re))stack.push(n.right);if(Number.isFinite(le))stack.push(n.left);}else{if(Number.isFinite(le))stack.push(n.left);if(Number.isFinite(re))stack.push(n.right);}}}if(best.hit)this.counters.hits++;this.counters.traceMs+=now()-t0;return best;}
  occluded(ray){this.counters.shadowRays++;if(!this.bvh.nodes.length)return false;const stack=[0];while(stack.length){const ni=stack.pop(),n=this.bvh.nodes[ni];this.counters.nodeTests++;if(!Number.isFinite(boxEntry(ray,n.bounds,ray.tMax??Infinity)))continue;if(n.leaf){for(let i=n.start;i<n.start+n.count;i++){const pi=this.bvh.indices[i],ti=this.bvh.primitives[pi].triangleIndex;this.counters.triangleTests++;if(triHit(this.store,ti,ray,Infinity)){this.counters.anyHits++;return true;}}}else{stack.push(n.left,n.right);}}return false;}
  snapshot(){const c=this.counters,total=Math.max(1,c.traceRays+c.shadowRays);return{version:'4.11.0',provider:'LitePix Core2 SAH BVH',triangles:this.triangleCount,nodes:this.nodeCount,buildMs:+this.buildMs.toFixed(3),traceRays:c.traceRays,shadowRays:c.shadowRays,nodeTests:c.nodeTests,triangleTests:c.triangleTests,hits:c.hits,anyHits:c.anyHits,avgNodeTests:+(c.nodeTests/total).toFixed(3),avgTriangleTests:+(c.triangleTests/total).toFixed(3),traceMs:+c.traceMs.toFixed(3),sah:this.bvh.stats()};}
}
root.LitePixCore2PathAcceleration411=LitePixCore2PathAcceleration411;
root.__LitePixCore2Path411=true;
})(typeof globalThis!=='undefined'?globalThis:window);
