(function(root){'use strict';
const Partial=root.LitePixCore2PartialAcceleration415;
if(typeof Partial!=='function')throw new Error('LitePix v4.16 requires Core2 v4.15');
const now=()=>root.performance?.now?.()??Date.now();
const same=(a,b)=>{if(!a||!b||a.length!==b.length)return false;for(let i=0;i<a.length;i++)if(a[i]!==b[i])return false;return true;};
const cp=o=>o?.transform?Array.from(o.transform):null;
function inv(m){const a=m[0],b=m[1],c=m[2],d=m[3],e=m[4],f=m[5],g=m[6],h=m[7],i=m[8],tx=m[9],ty=m[10],tz=m[11],A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,H=b*g-a*h,I=a*e-b*d,det=a*A+b*D+c*G;if(Math.abs(det)<1e-15)return null;const q=1/det,r=[A*q,B*q,C*q,D*q,E*q,F*q,G*q,H*q,I*q,0,0,0];r[9]=-(r[0]*tx+r[1]*ty+r[2]*tz);r[10]=-(r[3]*tx+r[4]*ty+r[5]*tz);r[11]=-(r[6]*tx+r[7]*ty+r[8]*tz);return r;}
const pt=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2]+m[9],m[3]*p[0]+m[4]*p[1]+m[5]*p[2]+m[10],m[6]*p[0]+m[7]*p[1]+m[8]*p[2]+m[11]];
function bounds(inst,m){const b=inst.blas.rootBounds,mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let x=0;x<2;x++)for(let y=0;y<2;y++)for(let z=0;z<2;z++){const p=pt(m,[x?b.max[0]:b.min[0],y?b.max[1]:b.min[1],z?b.max[2]:b.min[2]]);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[k]);mx[k]=Math.max(mx[k],p[k]);}}return{min:mn,max:mx};}
function fnv(h,a){if(!a)return Math.imul(h^255,16777619)>>>0;const v=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);h=Math.imul(h^(a.length>>>0),16777619)>>>0;for(let i=0;i<v.length;i++){h^=v[i];h=Math.imul(h,16777619)>>>0;}return h>>>0;}
function geomSig(scene){const out=[];for(const o of scene?.objects||[]){let h=2166136261>>>0,m=o?.localMesh;for(const a of [m?.positions,m?.normals,m?.uvs,m?.indices,m?.materialIndices])h=fnv(h,a);out.push(String(o?.id)+'|'+String(o?.geometryId)+'|'+(o?.materialIds?.length||0)+'|'+h.toString(16));}return out.join(';;');}
class SelectiveTLASCache416{
 constructor(){this.entry=null;this.selectiveRefits=0;this.nodesUpdated=0;this.fullDelegates=0;this.cleanReuses=0;this.lastMode='cold';this.lastDirty=[];this.lastMs=0;}
 reset(){this.entry=null;this.lastMode='reset';this.lastDirty=[];}
 _parents(inner){const p=new Int32Array(inner.nodes?.length||0);p.fill(-1);for(let i=0;i<p.length;i++){const n=inner.nodes[i];if(n&&!n.ids){if(n.left>=0)p[n.left]=i;if(n.right>=0)p[n.right]=i;}}return p;}
 _leafMap(inner){const m=new Map();for(let i=0;i<(inner.nodes?.length||0);i++){const ids=inner.nodes[i].ids;if(ids)for(const id of ids)m.set(id,i);}return m;}
 _delegate(base,job,sig){const a=Partial.wrap(base,job),inner=a.inner;this.entry={sig,inner,transforms:(job.renderScene?.objects||[]).map(cp),parents:this._parents(inner),leafMap:this._leafMap(inner)};this.fullDelegates++;return inner;}
 _recalcNode(inner,ni){const n=inner.nodes[ni];if(!n)return;if(n.ids){let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const id of n.ids){const b=inner.instances[id].bounds;for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],b.min[k]);mx[k]=Math.max(mx[k],b.max[k]);}}n.min=mn;n.max=mx;}else{const a=inner.nodes[n.left],b=inner.nodes[n.right];n.min=[Math.min(a.min[0],b.min[0]),Math.min(a.min[1],b.min[1]),Math.min(a.min[2],b.min[2])];n.max=[Math.max(a.max[0],b.max[0]),Math.max(a.max[1],b.max[1]),Math.max(a.max[2],b.max[2])];}}
 _selective(scene,dirty){const e=this.entry,inner=e.inner,touched=new Set();for(const oi of dirty){const ii=inner.instances.findIndex(x=>x.objectIndex===oi);if(ii<0)return false;const x=inner.instances[ii],m=cp(scene.objects[oi]),iv=inv(m);if(!iv)return false;x.transform=m;x.inverse=iv;x.bounds=bounds(x,m);let n=e.leafMap.get(ii);if(n===undefined)return false;while(n>=0){touched.add(n);n=e.parents[n];}}
 const order=[...touched].sort((a,b)=>b-a);for(const ni of order)this._recalcNode(inner,ni);inner.refitCount=(inner.refitCount||0)+1;this.selectiveRefits++;this.nodesUpdated+=touched.size;return touched.size;}
 prepare(base,job){const t=now(),scene=job?.renderScene,sig=geomSig(scene),next=(scene?.objects||[]).map(cp);let inner,mode='delegate',dirty=[];if(!this.entry||this.entry.sig!==sig){inner=this._delegate(base,job,sig);mode='delegate-geometry';dirty=next.map((_,i)=>i);}else{for(let i=0;i<next.length;i++)if(!same(next[i],this.entry.transforms[i]))dirty.push(i);inner=this.entry.inner;inner.base=base;inner.store=base?.store;inner.job=job;inner.traceRays=0;inner.shadowRays=0;if(dirty.length){const n=this._selective(scene,dirty);if(n===false){inner=this._delegate(base,job,sig);mode='delegate-fallback';}else{mode='selective-refit';this.entry.transforms=next;}}else{mode='reuse-clean';this.cleanReuses++;}job.litePixCore2Scene413=inner;}
 this.lastMode=mode;this.lastDirty=dirty;this.lastMs=now()-t;const a=new SelectiveTLASAcceleration416(inner,base,job,this);job.litePixCore2TLAS416=a;return a;}
 snapshot(){return{version:'4.16.0',provider:'LitePix Core2 selective TLAS',mode:this.lastMode,dirtyObjectIndices:this.lastDirty,dirtyCount:this.lastDirty.length,selectiveRefits:this.selectiveRefits,nodesUpdated:this.nodesUpdated,fullDelegates:this.fullDelegates,cleanReuses:this.cleanReuses,lastPrepareMs:+this.lastMs.toFixed(3)};}
}
class SelectiveTLASAcceleration416{constructor(inner,base,job,cache){this.inner=inner;this.base=base;this.store=base?.store||inner?.store;this.job=job;this.cache=cache;}static wrap(base,job){if(base instanceof SelectiveTLASAcceleration416)return base;if(job?.litePixCore2TLAS416?.base===base)return job.litePixCore2TLAS416;return LitePixCore2TLASCache416.prepare(base,job);}trace(r){return this.inner.trace(r);}occluded(r){return this.inner.occluded(r);}snapshot(){return{...(this.inner.snapshot?.()||{}),...this.cache.snapshot()};}}
const LitePixCore2TLASCache416=new SelectiveTLASCache416();
root.LitePixCore2TLASCache416=LitePixCore2TLASCache416;root.LitePixCore2TLASAcceleration416=SelectiveTLASAcceleration416;root.__LitePixCore2TLAS416=true;
})(typeof globalThis!=='undefined'?globalThis:window);