(function(root){'use strict';
const VERSION='4.48.0',clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(+v)?+v:0));
const lum=(a,o)=>.2126*(a[o]||0)+.7152*(a[o+1]||0)+.0722*(a[o+2]||0);
class L3NFeatureDenoiser448{
 constructor(opts={}){this.radius=Math.max(1,Math.min(3,opts.radius|0||1));this.lumaSigma=opts.lumaSigma??.12;this.depthSigma=opts.depthSigma??.05;this.albedoSigma=opts.albedoSigma??.18;this.normalPower=opts.normalPower??16;this.statsData={runs:0,pixels:0,meanAbsChange:0,maxAbsChange:0,edgeRejected:0,neighbors:0};}
 run(input){const w=input?.width|0,h=input?.height|0,beauty=input?.beauty;if(!w||!h||!beauty||beauty.length<w*h*3)throw new Error('L3N denoiser requires width,height and RGB beauty buffer');const variance=input.variance||null,normal=input.normal||null,depth=input.depth||null,albedo=input.albedo||null,material=input.materialId||null,out=new Float32Array(w*h*3);let sumChange=0,maxChange=0,edges=0,neighbors=0;const r=this.radius;
  for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,o=i*3,cv=Math.max(0,variance?.[i]??0),strength=clamp(.15+cv*6,.12,.9),cL=lum(beauty,o),cz=depth?.[i]??0,cm=material?.[i];let wr=1,wg=1,wb=1,ws=1,sr=beauty[o],sg=beauty[o+1],sb=beauty[o+2];for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const j=ny*w+nx,p=j*3;if(material&&cm!==material[j]){edges++;continue;}let wt=1/(1+dx*dx+dy*dy);const dL=Math.abs(lum(beauty,p)-cL);wt*=Math.exp(-dL/Math.max(1e-5,this.lumaSigma*(.4+strength)));if(depth){const dd=Math.abs((depth[j]??0)-cz)/Math.max(1e-5,Math.abs(cz)+1);wt*=Math.exp(-dd/Math.max(1e-5,this.depthSigma));if(dd>.08)edges++;}if(normal){const no=o,nj=p,dot=clamp((normal[no]||0)*(normal[nj]||0)+(normal[no+1]||0)*(normal[nj+1]||0)+(normal[no+2]||0)*(normal[nj+2]||0));wt*=Math.pow(dot,this.normalPower);if(dot<.7)edges++;}if(albedo){const da=Math.abs((albedo[o]||0)-(albedo[p]||0))+Math.abs((albedo[o+1]||0)-(albedo[p+1]||0))+Math.abs((albedo[o+2]||0)-(albedo[p+2]||0));wt*=Math.exp(-da/Math.max(1e-5,this.albedoSigma));}wt*=strength;if(wt<1e-7)continue;neighbors++;sr+=beauty[p]*wt;sg+=beauty[p+1]*wt;sb+=beauty[p+2]*wt;ws+=wt;}const nr=sr/ws,ng=sg/ws,nb=sb/ws;out[o]=nr;out[o+1]=ng;out[o+2]=nb;const ch=(Math.abs(nr-beauty[o])+Math.abs(ng-beauty[o+1])+Math.abs(nb-beauty[o+2]))/3;sumChange+=ch;maxChange=Math.max(maxChange,ch);}
  this.statsData={runs:this.statsData.runs+1,pixels:w*h,meanAbsChange:sumChange/(w*h),maxAbsChange:maxChange,edgeRejected:edges,neighbors};return{version:VERSION,width:w,height:h,beauty:out,stats:{...this.statsData}};}
 stats(){return{version:VERSION,...this.statsData};}
}
const inst=new L3NFeatureDenoiser448();root.L3NFeatureDenoiser448=L3NFeatureDenoiser448;root.__3DLiteL3NFeatureDenoiser=inst;root.__3DLiteL3NFeatureDenoiserVersion=VERSION;root.__3DLiteL3NDenoise=input=>inst.run(input);root.__3DLiteL3NDenoiseStats=()=>inst.stats();
})(typeof globalThis!=='undefined'?globalThis:window);
