(function(root){'use strict';
const VERSION='4.48.0',finite=v=>Number.isFinite(+v)?+v:null;
function install(){const health=root.LitePixRenderHealthDebugger,L=root.__3DLiteL3NRendering;if(!health||!L||health.__l3n448HealthInstalled)return false;health.__l3n448HealthInstalled=true;
  const baseSnapshot=health.snapshot.bind(health),baseText=health.toText.bind(health);
  health.snapshot=function(){const b=baseSnapshot(),l=root.__3DLiteL3NRenderingSnapshot?.()||null,g=root.__3DLiteRunL3NWorkflowGate?.()||null,i=root.__3DLiteL3NRenderIntegrationSnapshot?.()||null;return Object.freeze({...b,l3nRendering:l,l3nWorkflowGate:g,l3nIntegration:i,l3nEvidenceVersion:VERSION});};
  health.toText=function(report){const r=report||health.snapshot();let out=baseText(r),l=r.l3nRendering||root.__3DLiteL3NRenderingSnapshot?.();if(!l)return out;out+='\n\n[L3N RENDERING EVIDENCE v'+VERSION+']';out+='\nCompletion: '+String(l.convergence?.reason||'UNKNOWN');out+='\nBackend: '+String(l.backend?.name||'unknown')+' | workers '+String(l.backend?.workers??'—');out+='\nScores: correctness '+((l.scores?.correctness||0)*100).toFixed(1)+' | quality '+((l.scores?.quality||0)*100).toFixed(1)+' | performance '+((l.scores?.performance||0)*100).toFixed(1)+' | efficiency '+((l.scores?.efficiency||0)*100).toFixed(1)+' | confidence '+((l.scores?.confidence||0)*100).toFixed(1);out+='\nBottleneck: '+String(l.bottleneck?.name||'unknown');
    out+='\n\n[EXACT / DIRECT STAGE EVIDENCE]';const stages=l.stages||{};const keys=Object.keys(stages);if(!keys.length)out+='\nNOT MEASURED | No exact/direct stage hooks have fired yet';else for(const k of keys){const s=stages[k];out+='\n'+String(s.source||'measured').padEnd(18)+' | '+k+' | total '+Math.round(finite(s.totalMs)||0)+'ms | mean '+Math.round(finite(s.meanMs)||0)+'ms | count '+String(s.count??0);}
    out+='\n\n[RAY / TRAVERSAL EVIDENCE]';out+='\nRay classes: '+JSON.stringify(l.rays?.counts||{});out+='\nTraversal: '+JSON.stringify(l.rays?.traversal||{});out+='\nBounce histogram: '+JSON.stringify(l.rays?.bounces||{});out+='\nRussian roulette: '+JSON.stringify(l.rays?.roulette||{});out+='\nContribution histogram: '+JSON.stringify(l.rays?.contributionHistogram||{});
    out+='\n\n[COLOR / LIGHT EVIDENCE]';out+='\nRaw HDR luma: '+JSON.stringify(l.color?.rawHDR||{});out+='\nPost exposure luma: '+JSON.stringify(l.color?.postExposure||{});out+='\nPost display luma: '+JSON.stringify(l.color?.postDisplay||{});out+='\nPer-light: '+JSON.stringify(l.color?.lights||{});out+='\nSpot probes: '+JSON.stringify((l.color?.spotProbes||[]).slice(-8));
    out+='\n\n[CONVERGENCE / EFFICIENCY]';out+='\n'+JSON.stringify(l.convergence||{});out+='\n\n[CACHE CONFIDENCE]';out+='\n'+JSON.stringify(l.caches||{});
    out+='\n\n[L3N DIAGNOSIS]';if(!(l.diagnosis||[]).length)out+='\nNo active L3N diagnosis';else for(const d of l.diagnosis)out+='\n'+String(d.severity||'INFO').padEnd(8)+' | '+String(d.code||'')+' | '+String(d.message||'');
    const inferred=r.executionTimeline?.stages||[],bvhInf=inferred.find?.(x=>x.id==='acceleration'),bvhExact=stages['bvh-build'];if(bvhInf?.durationMs!=null&&bvhExact?.totalMs!=null){const a=+bvhInf.durationMs,e=+bvhExact.totalMs,ratio=Math.max(a,e)/Math.max(1,Math.min(a,e));if(ratio>2)out+='\nWARNING  | TIMELINE_DISAGREEMENT | inferred BVH '+Math.round(a)+'ms vs exact/direct '+Math.round(e)+'ms; trust exact/direct evidence';}
    const gate=r.l3nWorkflowGate;if(gate)out+='\n\n[L3N WORKFLOW GATE]\n'+(gate.passed?'PASS':'FAIL')+' '+gate.passedCount+'/'+gate.total;
    return out;
  };
  root.__3DLiteRenderHealthL3NVersion=VERSION;return true;}
if(!install()){let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>120)clearInterval(timer);},100);}
})(typeof globalThis!=='undefined'?globalThis:window);
