(function(root){'use strict';
const VERSION='4.48.0',MARK=Symbol.for('3dlite.l3n448.wrapped');
const now=()=>root.performance?.now?.()??Date.now();
const safe=(name,...args)=>{try{const f=root[name];if(typeof f==='function')return f(...args);}catch(_){}return undefined;};
const wrap=(proto,name,hooks={})=>{if(!proto||typeof proto[name]!=='function')return false;const current=proto[name];if(current[MARK])return true;const wrapped=function(...args){let ctx;try{ctx=hooks.before?.call(this,args);}catch(_){}let out;try{out=current.apply(this,args);}catch(e){try{hooks.error?.call(this,e,args,ctx);}catch(_){}throw e;}if(out&&typeof out.then==='function')return out.then(v=>{try{hooks.after?.call(this,v,args,ctx);}catch(_){}return v;},e=>{try{hooks.error?.call(this,e,args,ctx);}catch(_){}throw e;});try{hooks.after?.call(this,out,args,ctx);}catch(_){}return out;};wrapped[MARK]=true;wrapped.__l3nOriginal=current;proto[name]=wrapped;return true;};
const state={installed:new Set(),attempts:0,lastInstall:0};
function installRuntime(){const C=root.LitePixRuntime?.constructor||root.LitePixNative?.Runtime;if(!C?.prototype)return false;const p=C.prototype;if(state.installed.has('runtime'))return true;
 wrap(p,'compileScene',{before(){safe('__3DLiteL3NBeginStage','scene-translation',{source:'runtime'});},after(v){safe('__3DLiteL3NEndStage','scene-translation',{source:'runtime'});try{const m=this.scene?.budget?.snapshot?.();if(m)safe('__3DLiteL3NSetMemory',m);}catch(_){}},error(){safe('__3DLiteL3NEndStage','scene-translation',{source:'runtime-error'});}});
 wrap(p,'beginFrame',{before(){safe('__3DLiteL3NBeginStage','frame',{source:'runtime'});}});
 wrap(p,'endFrame',{after(){safe('__3DLiteL3NEndStage','frame',{source:'runtime'});}});
 wrap(p,'compileMaterial',{before(){safe('__3DLiteL3NBeginStage','material-compile',{source:'runtime'});},after(){safe('__3DLiteL3NEndStage','material-compile',{source:'runtime'});},error(){safe('__3DLiteL3NEndStage','material-compile',{source:'runtime-error'});}});
 state.installed.add('runtime');return true;}
function installAcceleration(){const C=root.LitePixCore2PathAcceleration412;if(!C?.prototype)return false;const p=C.prototype;if(state.installed.has('accel'))return true;
 const oldWrap=C.wrap;if(typeof oldWrap==='function'&&!oldWrap[MARK]){const nw=function(base,job){const v=oldWrap.call(this,base,job);try{if(v?.buildMs!=null)safe('__3DLiteL3NObserveStage','bvh-build',v.buildMs,{source:'core2-exact-measure',nodes:v.nodeCount,triangles:v.triangleCount});}catch(_){}return v;};nw[MARK]=true;nw.__l3nOriginal=oldWrap;C.wrap=nw;}
 wrap(p,'snapshot',{after(s){try{const c=this.counters||{},last=this.__l3nLastCounters||{nodeTests:0,triangleTests:0,hits:0,anyHits:0,traceRays:0,shadowRays:0};const d={nodeTests:Math.max(0,c.nodeTests-last.nodeTests),leafVisits:0,primitiveTests:Math.max(0,c.triangleTests-last.triangleTests),hits:Math.max(0,c.hits-last.hits),misses:Math.max(0,(c.traceRays-last.traceRays)-(c.hits-last.hits))};if(d.nodeTests||d.primitiveTests||d.hits||d.misses)safe('__3DLiteL3NTraversal',d);const sd=Math.max(0,c.shadowRays-last.shadowRays);if(sd)safe('__3DLiteL3NRay','shadow',sd);this.__l3nLastCounters={...c};if(s?.traceMs!=null)safe('__3DLiteL3NObserveStage','bvh-trace',s.traceMs,{source:'core2-counter-total'});if(s?.shadowMs!=null)safe('__3DLiteL3NObserveStage','shadow-traversal',s.shadowMs,{source:'core2-counter-total'});}catch(_){}}});
 state.installed.add('accel');return true;}
function installPathObserver(){const C=root.LitePixPathExecution410;if(!C?.prototype)return false;const p=C.prototype;if(state.installed.has('path410'))return true;
 wrap(p,'record',{before(args){const[index,x,y,sample,hit,acc]=args;try{safe('__3DLiteL3NRay','primary',1);const rad=sample?.radiance||[0,0,0];if((this.samples&255)===0)safe('__3DLiteL3NColor','raw',rad);if(acc&&index>=0){const variance=acc.samples?.[index]>1&&typeof acc.variance==='function'?acc.variance(index):1;const samples=acc.samples?.[index]||1;const noise=typeof acc.noise==='function'?acc.noise(index):variance;safe('__3DLiteL3NPixel',index,{variance:Number.isFinite(variance)?variance:1,luma:.2126*(rad[0]||0)+.7152*(rad[1]||0)+.0722*(rad[2]||0),samples,converged:Number.isFinite(noise)&&noise<=(this.opts?.noiseThreshold??.03)});}}catch(_){}return{sampleStart:this.samples,wallStart:this.__l3nPassWallStart??now()};},after(){if(this.__l3nPassWallStart==null)this.__l3nPassWallStart=now();}});
 wrap(p,'completePass',{before(){safe('__3DLiteL3NBeginStage','gi-pass',{source:'path410'});return{t:now(),sampleStart:this.__l3nLastPassSamples||0,wallStart:this.__l3nPassWallStart??now()};},after(s,args,ctx){safe('__3DLiteL3NEndStage','gi-pass',{source:'path410'});try{const acc=args[0],sampleDelta=Math.max(0,this.samples-(ctx?.sampleStart||0)),noise=typeof acc?.averageNoise==='function'?acc.averageNoise():0,active=Number(acc?.active??0),total=this.width*this.height,wall=Math.max(0,now()-(ctx?.wallStart??now()));safe('__3DLiteL3NPass',{pass:this.pass,timeMs:wall,rays:sampleDelta,noise,activePixels:active,totalPixels:total,samples:typeof acc?.averageSamples==='function'?acc.averageSamples():this.pass});this.__l3nLastPassSamples=this.samples;this.__l3nPassWallStart=now();if(s?.memory)safe('__3DLiteL3NSetMemory',s.memory);}catch(_){} }});
 wrap(p,'dispose',{before(){safe('__3DLiteL3NEndStage','path-render',{source:'path410-dispose'});}});
 state.installed.add('path410');return true;}
function installRayBudget(){const C=root.LitePixRayBudget445;if(!C?.prototype)return false;if(state.installed.has('raybudget'))return true;const p=C.prototype;
 wrap(p,'budgetFor',{after(v,args){try{const kind=String(args[0]||'sample'),base=Math.max(0,args[1]|0),extra=Math.max(0,(v|0)-base);if(extra)safe('__3DLiteL3NLearn',`ray-budget:${kind}`,`allocate extra work only where variance/luma requires it`,`${extra} extra samples granted`,'OBSERVED','LOW');}catch(_){} }});
 wrap(p,'snapshot',{after(s){try{if(s?.varianceLuma?.meanLuma!=null)safe('__3DLiteL3NColor','raw',[s.varianceLuma.meanLuma,s.varianceLuma.meanLuma,s.varianceLuma.meanLuma]);if(s?.shadowVerification?.checks){safe('__3DLiteL3NLearn','shadow-cache-verification','cached visibility should match physical verification rays',`${s.shadowVerification.mismatches}/${s.shadowVerification.checks} mismatches`,s.shadowVerification.mismatches?'REVIEW':'PASS',s.shadowVerification.checks>=16?'HIGH':'MEDIUM');}}catch(_){} }});
 state.installed.add('raybudget');return true;}
function installColor(){const C=root.LitePixNative?.Core6?.ColorPolicy;if(!C||state.installed.has('color'))return !!C;for(const name of ['toDisplay']){const orig=C[name];if(typeof orig!=='function'||orig[MARK])continue;let calls=0;const w=function(v,...rest){const out=orig.call(this,v,...rest);calls++;if((calls&1023)===0){safe('__3DLiteL3NColor','raw',v);safe('__3DLiteL3NColor','display',out);}return out;};w[MARK]=true;w.__l3nOriginal=orig;C[name]=w;}state.installed.add('color');return true;}
function installProduction(){const C=root.LitePixNative?.Core7?.ProductionQueue;if(!C?.prototype||state.installed.has('production'))return !!C;wrap(C.prototype,'run',{before(){safe('__3DLiteL3NBeginStage','production-queue',{source:'core7'});},after(){safe('__3DLiteL3NEndStage','production-queue',{source:'core7'});},error(){safe('__3DLiteL3NEndStage','production-queue',{source:'core7-error'});}});state.installed.add('production');return true;}
function installLegacyDirectLight(){const D=root.DirectLightSampler;if(!D||typeof D.sample!=='function'||D.sample[MARK]||state.installed.has('directlight'))return !!D;const orig=D.sample;let calls=0;const w=function(light,point,...rest){const t=now(),out=orig.call(this,light,point,...rest);calls++;try{const rad=out?.radiance||[0,0,0],c=.2126*(rad[0]||0)+.7152*(rad[1]||0)+.0722*(rad[2]||0);safe('__3DLiteL3NLight',light?.id??light?.uuid??light?.name??light?.type,c,{type:light?.type,distance:out?.distance,occluded:false,timeMs:now()-t});if(light?.type==='spot'&&(calls&63)===0)safe('__3DLiteL3NSpotProbe',{distance:out?.distance,distanceAttenuation:out?.attenuation,cone:out?.cone,ndl:out?.ndl,visibility:out?.visibility,bsdf:out?.bsdf,lightPdf:out?.pdf??out?.lightPdf,bsdfPdf:out?.bsdfPdf,mis:out?.mis??out?.misWeight,finalContribution:c});}catch(_){}return out;};w[MARK]=true;w.__l3nOriginal=orig;D.sample=w;state.installed.add('directlight');return true;}
function installLegacyRender(){const R=root.RenderFramework;if(!R||state.installed.has('renderframework'))return !!R;for(const name of ['render','startRender','renderPath','renderProgressive'])if(typeof R[name]==='function')wrap(R,name,{before(){safe('__3DLiteL3NBeginStage','render-total',{source:'RenderFramework',method:name});},after(v){safe('__3DLiteL3NEndStage','render-total',{source:'RenderFramework',method:name});},error(){safe('__3DLiteL3NEndStage','render-total',{source:'RenderFramework-error',method:name});}});state.installed.add('renderframework');return true;}
function install(){state.attempts++;state.lastInstall=Date.now();installRuntime();installAcceleration();installPathObserver();installRayBudget();installColor();installProduction();installLegacyDirectLight();installLegacyRender();try{safe('__3DLiteL3NSetBackend',{name:root.navigator?.gpu?'webgpu-available/backend-unconfirmed':'cpu-or-wasm',workers:0,hardwareConcurrency:root.navigator?.hardwareConcurrency||null});}catch(_){}return snapshot();}
function snapshot(){return{version:VERSION,installed:[...state.installed],attempts:state.attempts,lastInstall:state.lastInstall,coverage:{runtime:state.installed.has('runtime'),acceleration:state.installed.has('accel'),pathObserver:state.installed.has('path410'),rayBudget:state.installed.has('raybudget'),color:state.installed.has('color'),production:state.installed.has('production'),directLight:state.installed.has('directlight'),renderFramework:state.installed.has('renderframework')}};}
root.__3DLiteL3NRenderIntegrationVersion=VERSION;root.__3DLiteL3NInstallRenderIntegration=install;root.__3DLiteL3NRenderIntegrationSnapshot=snapshot;
install();if(typeof setInterval==='function'){try{if(root.__3DLiteL3NIntegrationTimer)clearInterval(root.__3DLiteL3NIntegrationTimer);root.__3DLiteL3NIntegrationTimer=setInterval(()=>{if(state.installed.size<8)install();},1000);}catch(_){}}
})(typeof globalThis!=='undefined'?globalThis:window);
