(function(root){'use strict';
const VERSION='4.48.0',MARK=Symbol.for('3dlite.l3n448.extra');
const now=()=>root.performance?.now?.()??Date.now();
const safe=(name,...args)=>{try{const f=root[name];if(typeof f==='function')return f(...args);}catch(_){}return undefined;};
const wrap=(proto,name,before,after)=>{if(!proto||typeof proto[name]!=='function')return false;const orig=proto[name];if(orig[MARK])return true;const fn=function(...args){let ctx;try{ctx=before?.call(this,args);}catch(_){}let v;try{v=orig.apply(this,args);}catch(e){try{after?.call(this,null,args,ctx,e);}catch(_){}throw e;}if(v&&typeof v.then==='function')return v.then(r=>{try{after?.call(this,r,args,ctx,null);}catch(_){}return r;},e=>{try{after?.call(this,null,args,ctx,e);}catch(_){}throw e;});try{after?.call(this,v,args,ctx,null);}catch(_){}return v;};fn[MARK]=true;fn.__l3nOriginal=orig;proto[name]=fn;return true;};
const state={installed:new Set(),attempts:0};
function gi(){const C=root.LitePixNative?.Core4?.HierarchicalGI,R=root.LitePixNative?.Core4?.RadianceCache;if(C?.prototype&&!state.installed.has('gi')){wrap(C.prototype,'runPass',function(){safe('__3DLiteL3NBeginStage','hierarchical-gi',{source:'Core4'});return{t:now(),before:this.stats?.()};},function(v,args,c){safe('__3DLiteL3NEndStage','hierarchical-gi',{source:'Core4'});const s=this.stats?.();if(s?.cache){const last=this.__l3nCacheLast||{hits:0,misses:0};const dh=Math.max(0,(s.cache.hits||0)-(last.hits||0)),dm=Math.max(0,(s.cache.misses||0)-(last.misses||0));if(dh)safe('__3DLiteL3NCache','radianceCache','hit',dh);if(dm)safe('__3DLiteL3NCache','radianceCache','miss',dm);this.__l3nCacheLast={hits:s.cache.hits||0,misses:s.cache.misses||0};}safe('__3DLiteL3NObserveStage','gi-refine',Math.max(0,now()-(c?.t??now())),{source:'Core4',active:s?.activeBlocks,finalized:s?.finalizedBlocks,refined:s?.refinedBlocks});});state.installed.add('gi');}
 if(R?.prototype&&!state.installed.has('radianceCache')){wrap(R.prototype,'clear',null,function(){safe('__3DLiteL3NCache','radianceCache','invalidate',1);});state.installed.add('radianceCache');}return !!C;}
function materials(){const C=root.LitePixNative?.Core6Production435;if(!C?.prototype||state.installed.has('materials'))return !!C;wrap(C.prototype,'compile',function(){safe('__3DLiteL3NBeginStage','material-preflight-compile',{source:'Core6Production'});return{t:now()};},function(){safe('__3DLiteL3NEndStage','material-preflight-compile',{source:'Core6Production'});});wrap(C.prototype,'auditTextures',function(args){safe('__3DLiteL3NBeginStage','texture-audit',{source:'Core6Production',count:Array.isArray(args[0])?args[0].length:0});return{t:now()};},function(){safe('__3DLiteL3NEndStage','texture-audit',{source:'Core6Production'});});state.installed.add('materials');return true;}
function aov(){const A=root.LitePixNative?.Core7?.AOVRegistry;if(!A?.prototype||state.installed.has('aov'))return !!A;wrap(A.prototype,'list',null,function(v){try{safe('__3DLiteL3NLearn','aov-registry','diagnostic AOVs should expose variance source and feature data',`${Array.isArray(v)?v.length:0} channels available`,'OBSERVED','MEDIUM');}catch(_){}});state.installed.add('aov');return true;}
function core2Scene(){const S=root.LitePixNative?.Core2?.SceneCompiler;if(!S?.prototype||state.installed.has('sceneCompiler'))return !!S;wrap(S.prototype,'compile',function(){safe('__3DLiteL3NBeginStage','scene-compiler-core2',{source:'Core2'});return{t:now()};},function(){safe('__3DLiteL3NEndStage','scene-compiler-core2',{source:'Core2'});try{const m=this.budget?.snapshot?.();if(m)safe('__3DLiteL3NSetMemory',m);}catch(_){}});state.installed.add('sceneCompiler');return true;}
function production435(){const C=root.LitePixNative?.Core7Production439||root.LitePixNative?.Core7Production;if(!C?.prototype||state.installed.has('core7prod'))return !!C;for(const n of ['compile','prepare','run','resolve','finalize'])if(typeof C.prototype[n]==='function')wrap(C.prototype,n,function(){safe('__3DLiteL3NBeginStage','core7-'+n,{source:'Core7Production'});return{t:now()};},function(){safe('__3DLiteL3NEndStage','core7-'+n,{source:'Core7Production'});});state.installed.add('core7prod');return true;}
function legacyAOV(){const U=root.RenderAOVUtil;if(!U||state.installed.has('legacyAOV'))return !!U;for(const n of ['writePrimary','primary'])if(typeof U[n]==='function'&&!U[n][MARK]){const o=U[n],f=function(...args){const v=o.apply(this,args);try{if(n==='primary'&&v?.Beauty)safe('__3DLiteL3NColor','raw',v.Beauty);}catch(_){}return v;};f[MARK]=true;f.__l3nOriginal=o;try{U[n]=f;}catch(_){}}state.installed.add('legacyAOV');return true;}
function legacyTrace(){const T=root.RenderPart5Core;if(!T||typeof T.trace!=='function'||T.trace[MARK]||state.installed.has('legacyTrace'))return !!T;const o=T.trace;let calls=0;const f=function(...args){const t=now(),v=o.apply(this,args);calls++;try{if((calls&127)===0){const r=v?.radiance||[0,0,0],L=.2126*(r[0]||0)+.7152*(r[1]||0)+.0722*(r[2]||0);safe('__3DLiteL3NContribution',L,128);safe('__3DLiteL3NObserveStage','path-trace-sampled',Math.max(0,now()-t),{source:'RenderPart5Core',sampledEvery:128});}}catch(_){}return v;};f[MARK]=true;f.__l3nOriginal=o;try{T.trace=f;state.installed.add('legacyTrace');}catch(_){}return state.installed.has('legacyTrace');}
function frameMetrics(){if(state.installed.has('frameCompare'))return true;root.__3DLiteL3NCompareFrames=function(base,candidate,opts={}){if(!base||!candidate||base.length!==candidate.length||!base.length)return{ok:false,reason:'incompatible buffers'};let mse=0,mae=0,max=0;for(let i=0;i<base.length;i++){const d=(+candidate[i]||0)-(+base[i]||0);mse+=d*d;mae+=Math.abs(d);max=Math.max(max,Math.abs(d));}mse/=base.length;mae/=base.length;const peak=opts.peak??1,psnr=mse===0?Infinity:10*Math.log10((peak*peak)/mse);return{ok:true,count:base.length,mse,mae,maxAbs:max,psnr,withinTolerance:max<=(opts.maxAbs??.02)&&mae<=(opts.mae??.005)};};state.installed.add('frameCompare');return true;}
function experiments(){if(state.installed.has('experimentRunner'))return true;root.__3DLiteL3NRunExperiment=async function(name,executor,change,opts={}){if(typeof executor!=='function')throw new Error('L3N experiment requires executor callback');const before=root.__3DLiteL3NRenderingSnapshot?.()||{},id=safe('__3DLiteL3NExperimentStart',name,{quality:before.scores?.quality||0,performance:before.scores?.performance||0,correctness:before.scores?.correctness||0});let baseResult,candidateResult,restore;try{baseResult=await executor({phase:'baseline'});if(typeof change==='function')restore=await change({phase:'candidate'});candidateResult=await executor({phase:'candidate'});}finally{try{if(typeof restore==='function')await restore();}catch(_){}}const after=root.__3DLiteL3NRenderingSnapshot?.()||{};const verdict=safe('__3DLiteL3NExperimentFinish',id,{quality:after.scores?.quality||0,performance:after.scores?.performance||0,correctness:after.scores?.correctness||0},opts);safe('__3DLiteL3NLearn',name,'candidate should improve verified quality/cost without correctness loss',JSON.stringify(verdict?.delta||{}),verdict?.verdict||'UNKNOWN',opts.confidence||'MEDIUM');return{version:VERSION,name,baseResult,candidateResult,verdict};};state.installed.add('experimentRunner');return true;}
function referenceContracts(){if(state.installed.has('references'))return true;const scenes=Object.freeze([
 {id:'spot-diffuse',purpose:'Spot attenuation/cone/visibility/exposure',requires:['spot','diffuse','direct','shadow','rawHDR','display']},
 {id:'soft-shadow',purpose:'Visibility-cache correctness and penumbra convergence',requires:['area-light','shadow','variance']},
 {id:'diffuse-gi',purpose:'Brute-force GI, Light Cache and guiding',requires:['diffuse','gi','indirect','variance']},
 {id:'mirror',purpose:'Reflection ray correctness and glossy energy',requires:['reflection','specular']},
 {id:'glass',purpose:'Refraction/transmission and RR',requires:['refraction','transmission']},
 {id:'many-lights',purpose:'Light Tree/reservoir activation threshold',requires:['light-tree','reservoirs']},
 {id:'display-ramp',purpose:'Linear HDR/exposure/tone/display transform',requires:['rawHDR','exposure','display']}
 ]);root.__3DLiteL3NReferenceContracts=scenes;root.__3DLiteL3NReferenceContract=id=>scenes.find(s=>s.id===id)||null;state.installed.add('references');return true;}
function install(){state.attempts++;gi();materials();aov();core2Scene();production435();legacyAOV();legacyTrace();frameMetrics();experiments();referenceContracts();return snapshot();}
function snapshot(){return{version:VERSION,installed:[...state.installed],attempts:state.attempts,coverage:{gi:state.installed.has('gi'),radianceCache:state.installed.has('radianceCache'),materials:state.installed.has('materials'),aov:state.installed.has('aov'),sceneCompiler:state.installed.has('sceneCompiler'),core7Production:state.installed.has('core7prod'),legacyAOV:state.installed.has('legacyAOV'),legacyTrace:state.installed.has('legacyTrace'),frameCompare:state.installed.has('frameCompare'),experimentRunner:state.installed.has('experimentRunner'),references:state.installed.has('references')}};}
root.__3DLiteL3NRenderIntegrationExtraVersion=VERSION;root.__3DLiteL3NInstallRenderIntegrationExtra=install;root.__3DLiteL3NRenderIntegrationExtraSnapshot=snapshot;install();if(typeof setInterval==='function'){try{if(root.__3DLiteL3NIntegrationExtraTimer)clearInterval(root.__3DLiteL3NIntegrationExtraTimer);root.__3DLiteL3NIntegrationExtraTimer=setInterval(()=>{if(state.installed.size<11)install();},1000);}catch(_){}}
})(typeof globalThis!=='undefined'?globalThis:window);
