(function(root){'use strict';
const VERSION='4.48.0';
const finite=(v,d=0)=>Number.isFinite(+v)?+v:d,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,finite(v))),lum=c=>Array.isArray(c)?.2126*finite(c[0])+.7152*finite(c[1])+.0722*finite(c[2]):.2126*finite(c?.r)+.7152*finite(c?.g)+.0722*finite(c?.b);
class RevisionPolicy{
 static decide(prev={},next={}){const p=prev||{},n=next||{};if(p.geometryTopologyRevision!==n.geometryTopologyRevision)return{action:'FULL_BLAS_REBUILD',reason:'topology changed'};if(p.geometryRevision!==n.geometryRevision)return{action:'PARTIAL_BLAS_REBUILD_OR_REFIT',reason:'geometry deformation changed'};if(p.transformRevision!==n.transformRevision||p.instanceRevision!==n.instanceRevision)return{action:'TLAS_REFIT',reason:'transform/instance changed'};if(p.materialRevision!==n.materialRevision||p.textureRevision!==n.textureRevision)return{action:'REUSE_ACCELERATION',reason:'shading-only change'};if(p.lightRevision!==n.lightRevision)return{action:'REUSE_ACCELERATION',reason:'light-only change'};if(p.cameraRevision!==n.cameraRevision)return{action:'REUSE_ACCELERATION',reason:'camera-only change'};return{action:'REUSE_ALL',reason:'no relevant revision changed'};}}
class ResidencyManager{
 constructor(limitBytes=512*1024*1024){this.limit=Math.max(1,limitBytes);this.used=0;this.items=new Map();this.clock=0;this.statsData={uploads:0,reuses:0,evictions:0,bytesUploaded:0,bytesEvicted:0,mipDowngrades:0};}
 touch(id,type,bytes,meta={}){id=String(id);bytes=Math.max(0,finite(bytes));this.clock++;let x=this.items.get(id);if(x){x.last=this.clock;x.meta={...x.meta,...meta};this.statsData.reuses++;return{x,reused:true};}this._ensure(bytes,type);x={id,type:String(type||'resource'),bytes,last:this.clock,priority:finite(meta.priority,1),mip:finite(meta.mip,0),meta:{...meta}};this.items.set(id,x);this.used+=bytes;this.statsData.uploads++;this.statsData.bytesUploaded+=bytes;return{x,reused:false};}
 _ensure(bytes,type){if(this.used+bytes<=this.limit)return;const candidates=[...this.items.values()].sort((a,b)=>(a.priority-b.priority)||(a.last-b.last));for(const x of candidates){if(this.used+bytes<=this.limit)break;if(x.meta.pinned)continue;this.items.delete(x.id);this.used-=x.bytes;this.statsData.evictions++;this.statsData.bytesEvicted+=x.bytes;}}
 remove(id){const x=this.items.get(String(id));if(!x)return false;this.items.delete(String(id));this.used-=x.bytes;return true;}
 mipFor(projectedPixels,fullSize=4096){const p=Math.max(1,finite(projectedPixels)),s=Math.max(1,finite(fullSize));return Math.max(0,Math.floor(Math.log2(Math.max(1,s/p))));}
 stats(){const byType={};for(const x of this.items.values())byType[x.type]=(byType[x.type]||0)+x.bytes;return{version:VERSION,limitBytes:this.limit,usedBytes:this.used,pressure:this.used/this.limit,count:this.items.size,byType,...this.statsData};}}
class AdaptiveWorkAllocator{
 constructor(opts={}){this.minWeight=finite(opts.minWeight,.12);this.maxExtra=Math.max(1,opts.maxExtra|0||8);this.weights={sample:1,shadow:1,direct:1,gi:1.2,reflection:1.15,refraction:1.05,bounce:.9,...opts.weights};}
 signal(ctx={}){const variance=Math.max(0,finite(ctx.variance??ctx.noise)),L=Math.max(0,finite(ctx.luma,lum(ctx.color??ctx.radiance??[0,0,0]))),V=clamp(variance*8),dark=1-clamp((L-.03)/.47),highlight=clamp((L-1)/3),feature=clamp(finite(ctx.normalEdge)+finite(ctx.depthEdge)+finite(ctx.materialEdge)+finite(ctx.roughnessEdge)),energy=ctx.throughput==null?1:clamp(Math.max(.03,lum(ctx.throughput)));const importance=clamp(Math.max(this.minWeight,V*(.58+.20*dark+.08*highlight+.08*feature+.06*energy)));return{variance,luma:L,V,dark,highlight,feature,energy,importance};}
 budget(kind,base=1,ctx={}){const s=this.signal(ctx),b=Math.max(0,base|0),converged=ctx.converged===true||(ctx.sampleCount>1&&s.V<.03&&s.feature<.05);if(converged)return{requested:b,granted:kind==='sample'?0:Math.min(1,b),signal:s,reason:'converged'};const w=finite(this.weights[kind],1),extra=Math.round(this.maxExtra*s.importance*w);return{requested:b,granted:b+extra,extra,signal:s,reason:'variance+luma+feature'};}
 redistribute(regions=[],totalBudget=0){const scored=regions.map((r,i)=>({i,r,s:this.signal(r)}));const sum=scored.reduce((a,x)=>a+x.s.importance,0)||1;return scored.map(x=>({index:x.i,budget:Math.floor(totalBudget*x.s.importance/sum),importance:x.s.importance}));}}
class DenoiseGuide{
 weight(ctx={}){const variance=clamp(finite(ctx.variance)*8),L=Math.max(0,finite(ctx.luma,lum(ctx.color||[0,0,0]))),dark=1-clamp((L-.04)/.5),edge=clamp(finite(ctx.normalEdge)+finite(ctx.depthEdge)+finite(ctx.materialEdge)),spec=clamp(finite(ctx.specular)+finite(ctx.reflection));return clamp(.62*variance+.25*dark-.35*edge-.25*spec+.12);}
 preserve(ctx={}){return clamp(finite(ctx.normalEdge)+finite(ctx.depthEdge)+finite(ctx.materialEdge)+finite(ctx.specular)+finite(ctx.reflection));}}
class CompletionPolicy{
 classify(s={}){const status=String(s.status||'').toLowerCase(),noise=finite(s.noise,Infinity),target=finite(s.targetNoise??s.noiseTarget,0),cur=finite(s.currentSamples),max=finite(s.maximumSamples);if(status.includes('cancel'))return'CANCELLED';if(status.includes('error')||status.includes('fail'))return'ERROR';if(s.timeLimitReached)return'TIME_LIMIT';if(s.memoryLimitReached)return'MEMORY_LIMIT';if(target>0&&noise<=target)return'CONVERGED';if(max>0&&cur>=max)return'MAX_SAMPLES_NOT_CONVERGED';return status.includes('finish')?'FINISHED_UNCLASSIFIED':'RUNNING';}
 shouldContinue(s={}){const reason=this.classify(s);return reason==='RUNNING'||reason==='MAX_SAMPLES_NOT_CONVERGED'&&s.allowAdaptiveExtension===true;}}
class EfficiencyModel{
 constructor(){this.history=[];}add(d={}){const row={at:Date.now(),stage:String(d.stage||'unknown'),timeMs:Math.max(0,finite(d.timeMs)),rays:Math.max(0,finite(d.rays)),before:Math.max(0,finite(d.varianceBefore??d.noiseBefore)),after:Math.max(0,finite(d.varianceAfter??d.noiseAfter))};row.gain=Math.max(0,row.before-row.after);row.gainPerMs=row.timeMs?row.gain/row.timeMs:0;row.gainPerMillionRays=row.rays?row.gain/(row.rays/1e6):0;this.history.push(row);if(this.history.length>512)this.history.shift();return row;}best(){return[...this.history].sort((a,b)=>(b.gainPerMs-a.gainPerMs)||(b.gainPerMillionRays-a.gainPerMillionRays))[0]||null;}snapshot(){return{version:VERSION,best:this.best(),history:this.history.slice(-64)};}}
class DecisionEngine{
 recommend(snapshot={}){const out=[],d=snapshot.diagnosis||[],c=snapshot.convergence||{},b=snapshot.bottleneck||{},cache=snapshot.caches||{},color=snapshot.color||{};if(c.reason==='MAX_SAMPLES_NOT_CONVERGED')out.push({priority:100,action:'ADAPTIVE_EXTEND',why:'sample ceiling reached before target noise'});if(d.some(x=>x.code==='SHADOW_REUSE_AGGRESSIVE'))out.push({priority:95,action:'VERIFY_SHADOW_CACHE',why:'visibility reuse exceeds confidence threshold'});if(color.rawHDR?.p50!=null&&color.postDisplay?.p50!=null&&color.rawHDR.p50>0&&color.postDisplay.p50<color.rawHDR.p50*.1)out.push({priority:94,action:'CHECK_EXPOSURE_DISPLAY',why:'raw HDR is substantially brighter than display output'});if(color.rawHDR?.p50===0&&Object.keys(color.lights||{}).length)out.push({priority:93,action:'CHECK_LIGHT_TRANSPORT',why:'raw HDR remains dark despite active lights'});if(b.name==='bvh-build')out.push({priority:90,action:'ACCELERATION_REUSE_REFIT',why:'BVH build dominates measured time'});if(d.some(x=>x.code==='LOW_RPS'))out.push({priority:80,action:'PROFILE_TRAVERSAL_AND_BACKEND',why:'ray throughput is low'});if(c.pixels?.activeRatio>.98&&c.passCount>2)out.push({priority:78,action:'FIX_CONVERGENCE_MASK',why:'adaptive sampler is not retiring stable pixels'});if(cache.shadowVisibility?.verificationErrorRate>0)out.push({priority:100,action:'REDUCE_SHADOW_REUSE',why:'physical verification rays disagree with cached visibility'});return out.sort((a,b)=>b.priority-a.priority);}}
class Optimizer448{
 constructor(){this.revisions=RevisionPolicy;this.residency=new ResidencyManager();this.allocator=new AdaptiveWorkAllocator();this.denoise=new DenoiseGuide();this.completion=new CompletionPolicy();this.efficiency=new EfficiencyModel();this.decisions=new DecisionEngine();}
 snapshot(){const l=root.__3DLiteL3NRenderingSnapshot?.()||{};return{version:VERSION,residency:this.residency.stats(),efficiency:this.efficiency.snapshot(),recommendations:this.decisions.recommend(l)};}}
const inst=new Optimizer448();root.L3NRenderOptimizer448=Optimizer448;root.__3DLiteL3NRenderOptimizer=inst;root.__3DLiteL3NRenderOptimizerVersion=VERSION;root.__3DLiteL3NAccelerationDecision=(a,b)=>RevisionPolicy.decide(a,b);root.__3DLiteL3NResidencyTouch=(...a)=>inst.residency.touch(...a);root.__3DLiteL3NResidencyStats=()=>inst.residency.stats();root.__3DLiteL3NAdaptiveBudget=(...a)=>inst.allocator.budget(...a);root.__3DLiteL3NRedistributeBudget=(...a)=>inst.allocator.redistribute(...a);root.__3DLiteL3NDenoiseWeight=x=>inst.denoise.weight(x);root.__3DLiteL3NCompletion=x=>inst.completion.classify(x);root.__3DLiteL3NEfficiency=x=>inst.efficiency.add(x);root.__3DLiteL3NRenderRecommendations=()=>inst.decisions.recommend(root.__3DLiteL3NRenderingSnapshot?.()||{});root.__3DLiteL3NRenderOptimizerSnapshot=()=>inst.snapshot();
})(typeof globalThis!=='undefined'?globalThis:window);
