(function(root){'use strict';
const VERSION='4.48.0';
class L3NRenderSession448{
 constructor(){this.active=null;this.history=[];this.lastStatus='';this.lastRenderId=null;this.timer=null;this.install();}
 install(){try{root.addEventListener?.('litepix:production-start',e=>this.start(e.detail));root.addEventListener?.('litepix:production-done',e=>this.finish(e.detail,'Finished'));root.addEventListener?.('litepix:production-error',e=>this.finish(e.detail,'Error'));}catch(_){}if(typeof setInterval==='function')this.timer=setInterval(()=>this.poll(),500);return this;}
 start(job={}){try{root.__3DLiteL3NRenderingReset?.();}catch(_){}this.active={id:job?.id??null,startedAt:Date.now(),job:job?.id??null};this.lastRenderId=this.active.id;this.lastStatus='Running';try{root.__3DLiteL3NBeginStage?.('render-session',{source:'session448',renderId:this.active.id});}catch(_){}return this.active;}
 poll(){let h;try{h=root.__3DLiteRenderHealth?.();}catch(_){return;}if(!h)return;const r=h.render||h.lifecycle||h,status=String(r.status??h.status??''),id=r.renderId??h.renderId??null;if(id!=null&&id!==this.lastRenderId&&/render|running|progress|trace|sampling/i.test(status))this.start({id});if(/complete|finished|done|cancel|error|fail/i.test(status)&&status!==this.lastStatus)this.finish({id,health:h},status);this.lastStatus=status;}
 finish(job={},status='Finished'){const h=job?.health||(()=>{try{return root.__3DLiteRenderHealth?.();}catch(_){return null;}})()||{},s=h.sampling||h.convergence||{},r=h.render||h.lifecycle||h;try{root.__3DLiteL3NFinish?.({status,noise:s.noise??h.noise,noiseTarget:s.noiseTarget??h.noiseTarget,currentSamples:s.currentSamples??h.currentSamples,maximumSamples:s.maximumSamples??h.maximumSamples,timeLimitReached:!!(r.timeLimitReached??h.timeLimitReached)});}catch(_){}try{root.__3DLiteL3NEndStage?.('render-session',{source:'session448',status});}catch(_){}const snap=root.__3DLiteL3NRenderingSnapshot?.()||null,gate=root.__3DLiteRunL3NWorkflowGate?.()||null,recommendations=root.__3DLiteL3NRenderRecommendations?.()||[];const row={version:VERSION,id:job?.id??this.active?.id??null,startedAt:this.active?.startedAt??null,finishedAt:Date.now(),status,completion:snap?.convergence?.reason||status,gate:gate?{passed:gate.passed,passedCount:gate.passedCount,total:gate.total}:null,recommendations,snapshot:snap};this.history.push(row);if(this.history.length>32)this.history.shift();try{root.__3DLiteL3NRecordRenderEvidence?.({renderId:row.id,status,completion:row.completion,gate:row.gate});}catch(_){}try{root.dispatchEvent?.(new CustomEvent('3dlite:l3n-render-evidence',{detail:row}));}catch(_){}this.active=null;return row;}
 snapshot(){return{version:VERSION,active:this.active?{...this.active}:null,last:this.history[this.history.length-1]||null,history:this.history.slice(-8)};}
}
const inst=new L3NRenderSession448();root.L3NRenderSession448=L3NRenderSession448;root.__3DLiteL3NRenderSession=inst;root.__3DLiteL3NRenderSessionVersion=VERSION;root.__3DLiteL3NRenderSessionSnapshot=()=>inst.snapshot();
})(typeof globalThis!=='undefined'?globalThis:window);
