import assert from 'node:assert/strict';
import { ThreeDLiteMainCore } from '../src/core/main-core.mjs';
import { RenderScenePort } from '../src/ports/render-scene-port.mjs';
const core=new ThreeDLiteMainCore(); const render=new RenderScenePort(core);
const geometry=core.createGeometry({id:'quad-geo',name:'Quad',positions:[[0,0,0],[1,0,0],[1,1,0],[0,1,0]],faces:[[0,1,2,3]]});
assert.equal(core.geometry.has(geometry),true); assert.equal(core.geometry.get(geometry).topology.halfEdges.length,4); assert.equal(core.geometry.get(geometry).triangles.length,6);
core.evaluator.registerOperator('offset',(input,params)=>({...input,positions:input.positions.map(p=>[p[0]+(params.x??0),p[1],p[2]])}));
const evaluatedA=core.evaluateGeometry(geometry,[{type:'offset',params:{x:3}}]);
const evaluatedB=core.evaluateGeometry(geometry,[{type:'offset',params:{x:3}}]);
assert.equal(evaluatedA.positions[0][0],3); assert.equal(evaluatedA,evaluatedB); assert.equal(core.geometry.get(geometry).positions[0][0],0,'evaluation must not mutate authoring geometry'); assert.equal(core.evaluator.stats().hits,1);
core.evaluationGraph.register('authoring'); core.evaluationGraph.register('modifier',['authoring']); core.evaluationGraph.register('render',['modifier']); assert.deepEqual(core.evaluationGraph.order(['render']),['authoring','modifier','render']); assert.throws(()=>core.evaluationGraph.register('authoring',['render']),/cycle/i);
const handle=core.createEntity({id:'a',type:'mesh',geometry,transform:{position:[0,0,0]}}); assert.equal(core.entities.has(handle),true);
const first=render.compile(); assert.equal(first.objects.length,1); assert.equal(first.objects[0].geometry.topology.faceCount,1); assert.equal(first.objects[0].geometry.triangles.length,6); const firstStamp=first.stamp.renderScene;
core.updateEntity(handle,e=>{e.transform.position[0]=1;},['transform','renderScene']); const second=render.compile(); assert.notEqual(second.stamp.renderScene,firstStamp); assert.equal(second.objects[0].transform.position[0],1);
const geometryStamp=second.stamp.geometry; core.updateGeometry(geometry,m=>{m.positions[0]=[-1,0,0];}); const third=render.compile(); assert.notEqual(third.stamp.geometry,geometryStamp); assert.equal(third.objects[0].geometry.positions[0][0],-1); assert.equal(core.destroyGeometry(geometry),false);
core.setSelection([handle,handle]); assert.equal(core.state.selection.length,1); core.setEditMode('vertex',geometry); core.setComponentSelection([0,1,1]); assert.deepEqual(core.state.editSelection.elements,[0,1]);
const beforeMove=core.geometry.get(geometry).positions.map(p=>p.slice()); core.moveSelectedVertices([0,0,2]); assert.equal(core.geometry.get(geometry).positions[0][2],beforeMove[0][2]+2); assert.equal(core.undo(),true); assert.deepEqual(core.geometry.get(geometry).positions,beforeMove); assert.equal(core.redo(),true);
core.setEditMode('edge',geometry); core.setComponentSelection([0,2]); assert.throws(()=>core.setComponentSelection([999]),/out of range/i); core.setEditMode('polygon',geometry); core.setComponentSelection([0]); core.setEditMode('object');
let value=0; const command={do(){value+=1;},undo(){value-=1;}}; core.execute(command); assert.equal(core.undo(),true); assert.equal(core.redo(),true); assert.equal(value,1);
assert.throws(()=>core.createGeometry({positions:[[0,0,0],[1,0,0],[0,1,0]],faces:[[0,1,4]]}),/invalid vertex indices/i);
core.assignGeometry(handle,null); assert.equal(core.destroyGeometry(geometry),true); core.destroyEntity(handle); assert.equal(render.compile().objects.length,0);
console.log('3D Lite Clean Rewrite core + geometry + edit + evaluation smoke: PASS');
