[package]
name = "threedlite-desktop"
version = "4.49.2"
description = "3DLite desktop shell"
authors = ["3dmk"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
