from pathlib import Path
import re,sys
p=Path('index.html')
s=p.read_text(encoding='utf-8',errors='ignore')
seg=int(sys.argv[1])
if not 1<=seg<=10: raise SystemExit('segment 1..10')

blocks={
1:r'''<script id="l3n-adaptive-segment-1">
(()=>{const V='3.99.0';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const state={version:V,renderCount:0,passCount:0,last:null,history:[],strategy:null,sceneRevision:0,learned:{},metrics:{}};
const A={version:V,state,clamp,now:()=>performance.now(),safe:n=>Number.isFinite(Number(n))?Number(n):0,
observe(sample={}){const x={at:Date.now(),renderId:sample.renderId??null,pass:this.safe(sample.currentSamples||sample.pass||0),max:this.safe(sample.maximumSamples||0),noise:this.safe(sample.noise),elapsedMs:this.safe(sample.elapsedMs),rays:this.safe(sample.totalRays||sample.raysCast),shadowRays:this.safe(sample.shadowRays),secondaryRays:this.safe(sample.secondaryRays),reflectionRays:this.safe(sample.reflectionRays),refractionRays:this.safe(sample.refractionRays),rps:this.safe(sample.raysPerSecond)};const prev=state.last;if(prev&&x.pass!==prev.pass)state.passCount++;state.last=x;state.history.push(x);if(state.history.length>512)state.history.splice(0,state.history.length-512);this.rebuild?.();return x;},
rebuild(){const h=state.history,cur=h[h.length-1]||{};const prev=h.length>1?h[h.length-2]:null;const noiseGain=prev?Math.max(0,(prev.noise||0)-(cur.noise||0)):0;const dt=prev?Math.max(1,(cur.elapsedMs||0)-(prev.elapsedMs||0)):1;state.metrics={noiseGain,deltaMs:dt,efficiency:noiseGain/dt};state.strategy=this.buildNextRenderStrategy?.(cur,h)||state.strategy;return state.strategy;},
buildNextRenderStrategy(cur,h){return {pass:cur.pass||0,rayBudget:1,activePixelRatio:1,activeTileRatio:1,lightBudget:1,bounceBudget:1,cacheReuse:0,guiding:0,efficiency:state.metrics.efficiency||0};},
snapshot(){return JSON.parse(JSON.stringify({version:V,state}));},invalidate(reason='scene-change'){state.sceneRevision++;state.learned={};state.strategy=null;return reason;}};
window.ThreeDLiteAdaptiveRender3990=A;window.__3DLiteAdaptiveRender3990=true;
function bind(){const rf=window.RenderFramework;if(!rf)return false;if(rf.__adaptive3990)return true;rf.__adaptive3990=true;const old=rf.ui?.updateProgress?.bind(rf.ui);if(old)rf.ui.updateProgress=(p)=>{const r=old(p);try{A.observe(p||{});}catch(_){}return r;};const rec=rf.recordCompleted?.bind(rf);if(rec)rf.recordCompleted=(job)=>{const r=rec(job);try{A.state.renderCount++;A.observe(job?.progress?.snapshot?.()||job?.progress||{});}catch(_){}return r;};return true;}
if(!bind())window.addEventListener('load',()=>bind(),{once:true});
})();</script>''',
2:r'''<script id="l3n-adaptive-segment-2">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.convergence={pixels:new Map(),tiles:new Map(),stableThreshold:.0025};
A.updateConvergence=(key,variance,cost=1,type='pixel')=>{const m=type==='tile'?S.convergence.tiles:S.convergence.pixels;const old=m.get(key)||{variance:1,samples:0,cost:0,stable:false};old.variance=.75*old.variance+.25*Math.max(0,variance||0);old.samples++;old.cost+=cost;old.stable=old.samples>2&&old.variance<S.convergence.stableThreshold;m.set(key,old);return old;};
A.convergenceSummary=()=>{const vals=[...S.convergence.tiles.values()];const stable=vals.filter(v=>v.stable).length;return {tiles:vals.length,stable,active:Math.max(0,vals.length-stable),ratio:vals.length?1-stable/vals.length:1};};
const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h),c=A.convergenceSummary();x.activeTileRatio=A.clamp(c.ratio,.05,1);x.activePixelRatio=A.clamp(c.ratio*.9+.1,.05,1);x.skipStablePixels=true;x.tilePriority='variance/cost';return x;};
})();</script>''',
3:r'''<script id="l3n-adaptive-segment-3">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;A.passBudget=(pass,noise)=>{const p=Math.max(1,pass||1);let b=p<=2?1:p<=4?.8:p<=8?.6:p<=16?.4:p<=32?.25:p<=48?.15:.1;if((noise||0)>.08)b=Math.max(b,.5);return A.clamp(b,.08,1);};const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h);x.rayBudget=A.passBudget(cur.pass,cur.noise);x.shadowBudget=A.clamp(.2+.8*x.rayBudget,.15,1);x.secondaryBudget=A.clamp(.15+.85*x.rayBudget,.1,1);return x;};
})();</script>''',
4:r'''<script id="l3n-adaptive-segment-4">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.lightLearning={lights:new Map(),minContribution:.002};A.learnLight=(id,contribution,visible=true,cost=1)=>{const m=S.lightLearning.lights,o=m.get(id)||{energy:0,visible:0,blocked:0,samples:0,cost:0};o.energy=.8*o.energy+.2*Math.max(0,contribution||0);visible?o.visible++:o.blocked++;o.samples++;o.cost+=cost;m.set(id,o);return o;};A.lightScore=id=>{const o=S.lightLearning.lights.get(id);if(!o)return 1;const vis=o.visible/Math.max(1,o.samples);return (o.energy+.001)*(vis+.05)/Math.max(.25,o.cost/o.samples);};A.shouldSampleLight=id=>A.lightScore(id)>=S.lightLearning.minContribution;const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h);x.lightBudget=A.clamp(.2+.8*x.rayBudget,.15,1);x.lightPolicy='importance+visibility+contribution';x.lightCutoff=S.lightLearning.minContribution;return x;};
})();</script>''',
5:r'''<script id="l3n-adaptive-segment-5">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.pathLearning={depth:new Map(),energyCutoff:.01};A.learnBounce=(depth,energy,useful=true)=>{const o=S.pathLearning.depth.get(depth)||{energy:0,useful:0,total:0};o.energy=.8*o.energy+.2*Math.max(0,energy||0);o.total++;if(useful)o.useful++;S.pathLearning.depth.set(depth,o);return o;};A.bounceAllowed=(depth,throughput=1)=>{if(throughput<S.pathLearning.energyCutoff)return false;const o=S.pathLearning.depth.get(depth);return !o||o.energy>=S.pathLearning.energyCutoff||o.useful/Math.max(1,o.total)>.08;};A.learnedMaxDepth=()=>{let d=2;for(const [k,v] of S.pathLearning.depth)if(v.energy>=S.pathLearning.energyCutoff||v.useful/Math.max(1,v.total)>.08)d=Math.max(d,Number(k));return Math.min(12,d+1);};const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h);x.bounceBudget=A.clamp(.25+.75*x.rayBudget,.2,1);x.maxUsefulDepth=A.learnedMaxDepth();x.energyCutoff=S.pathLearning.energyCutoff;return x;};
})();</script>''',
6:r'''<script id="l3n-adaptive-segment-6">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.noiseLearning={direct:0,shadow:0,gi:0,reflection:0,refraction:0};A.learnNoise=(type,value)=>{if(type in S.noiseLearning)S.noiseLearning[type]=.75*S.noiseLearning[type]+.25*Math.max(0,value||0);return S.noiseLearning;};A.materialProfile=(m={})=>{const r=Number(m.roughness??.5),metal=Number(m.metalness??0),trans=Number(m.transmission??0);return {direct:1,gi:A.clamp(.7+r*.3,.5,1),reflection:A.clamp(.2+metal*.5+(1-r)*.5,.15,1),refraction:A.clamp(trans,0,1)};};const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h),n=S.noiseLearning,total=Object.values(n).reduce((a,b)=>a+b,0)||1;x.effectBudget={direct:.2+n.direct/total,shadow:.2+n.shadow/total,gi:.2+n.gi/total,reflection:.2+n.reflection/total,refraction:.2+n.refraction/total};x.noiseDirected=true;return x;};
})();</script>''',
7:r'''<script id="l3n-adaptive-segment-7">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.cache={primary:new Map(),visibility:new Map(),revision:0,hits:0,misses:0};A.cacheKey=(...v)=>v.join('|');A.cacheGet=(kind,key)=>{const m=S.cache[kind];if(!m)return null;const v=m.get(key);v?S.cache.hits++:S.cache.misses++;return v||null;};A.cacheSet=(kind,key,value)=>{const m=S.cache[kind];if(m)m.set(key,{revision:S.sceneRevision,value});return value;};const inv=A.invalidate.bind(A);A.invalidate=(reason)=>{S.cache.primary.clear();S.cache.visibility.clear();S.cache.revision++;return inv(reason);};const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h),t=S.cache.hits+S.cache.misses;x.cacheReuse=t?S.cache.hits/t:0;x.reusePrimaryHits=true;x.reuseBVH=true;x.reuseVisibility=true;return x;};
})();</script>''',
8:r'''<script id="l3n-adaptive-segment-8">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const S=A.state;S.guiding={dirs:new Map(),reservoirs:new Map()};A.learnDirection=(bucket,dir,energy)=>{const a=S.guiding.dirs.get(bucket)||[];a.push({dir,energy:Math.max(0,energy||0)});a.sort((x,y)=>y.energy-x.energy);if(a.length>16)a.length=16;S.guiding.dirs.set(bucket,a);return a;};A.guideDirection=bucket=>S.guiding.dirs.get(bucket)?.[0]?.dir||null;A.updateReservoir=(key,candidate,weight)=>{const r=S.guiding.reservoirs.get(key)||{sum:0,sample:null,count:0};r.sum+=Math.max(0,weight||0);r.count++;if(!r.sample||Math.random()*r.sum<weight)r.sample=candidate;S.guiding.reservoirs.set(key,r);return r.sample;};const base=A.buildNextRenderStrategy.bind(A);A.buildNextRenderStrategy=(cur,h)=>{const x=base(cur,h);x.guiding=A.clamp((cur.pass||0)/16,0,1);x.usePathGuiding=(cur.pass||0)>=4;x.useLightReservoirs=(cur.pass||0)>=2;return x;};
})();</script>''',
9:r'''<script id="l3n-adaptive-segment-9">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;A.efficiencyScore=(gain,cost)=>Math.max(0,gain||0)/Math.max(1,cost||1);A.chooseStrategy=(current,previous)=>{if(!current)return null;const next={...current};const e=current.efficiency||0,pe=previous?.efficiency||0;if(pe>0&&e<pe*.7){next.rayBudget=A.clamp(current.rayBudget*.8,.08,1);next.adaptation='reduce-low-yield-work';}else if(e>pe*1.1){next.rayBudget=A.clamp(current.rayBudget*1.05,.08,1);next.adaptation='keep-high-yield-work';}else next.adaptation='hold';return next;};const base=A.rebuild.bind(A);A.rebuild=()=>{const old=A.state.strategy;const r=base();A.state.strategy=A.chooseStrategy(r,old)||r;return A.state.strategy;};A.state.controllerMode='quality-gain-per-ms';
})();</script>''',
10:r'''<script id="l3n-adaptive-segment-10">
(()=>{const A=window.ThreeDLiteAdaptiveRender3990;if(!A)return;const $=id=>document.getElementById(id);A.compiledCode=()=>{const snap=A.snapshot(),st=snap.state.strategy||{};return `// 3DLite Adaptive Render Learned Profile v${A.version}\nconst AdaptiveProfile=${JSON.stringify({version:A.version,sceneRevision:snap.state.sceneRevision,renderCount:snap.state.renderCount,passCount:snap.state.passCount,strategy:st,metrics:snap.state.metrics,learned:snap.state.learned},null,2)};\n\n// Apply through window.ThreeDLiteAdaptiveRender3990 on next render.\n`;};A.openCodeViewer=()=>{let p=$('l3nAdaptiveCodeWindow3990');if(!p){p=document.createElement('div');p.id='l3nAdaptiveCodeWindow3990';p.style.cssText='display:none;position:absolute;left:16px;right:16px;top:48px;bottom:16px;z-index:80;background:#181818;border:1px solid #555;padding:8px;box-shadow:0 8px 28px #000b';p.innerHTML='<div style="display:flex;gap:6px;align-items:center;margin-bottom:6px"><b style="margin-right:auto">Compiled Adaptive Render Code</b><button id="l3nAdaptiveRefresh3990">Refresh</button><button id="l3nAdaptiveCopy3990">Copy All</button><button id="l3nAdaptiveClose3990">Close</button></div><textarea id="l3nAdaptiveCodeText3990" spellcheck="false" style="width:100%;height:calc(100% - 34px);resize:none;background:#101010;color:#ddd;border:1px solid #444;font:11px/1.35 monospace;padding:8px"></textarea>';($('renderFrameWindow')||document.body).appendChild(p);$('l3nAdaptiveRefresh3990').onclick=()=>{$('l3nAdaptiveCodeText3990').value=A.compiledCode()};$('l3nAdaptiveCopy3990').onclick=async()=>{const t=$('l3nAdaptiveCodeText3990');t.select();try{await navigator.clipboard.writeText(t.value)}catch(_){document.execCommand('copy')}};$('l3nAdaptiveClose3990').onclick=()=>p.style.display='none';}p.style.display='block';$('l3nAdaptiveCodeText3990').value=A.compiledCode();return p;};
function button(){const title=$('renderFrameWindow')?.querySelector('.render-title');if(!title||$('l3nAdaptiveCodeBtn3990'))return;const b=document.createElement('button');b.id='l3nAdaptiveCodeBtn3990';b.type='button';b.textContent='Adaptive Code';b.title='Open compiled adaptive render learning code';b.onclick=()=>A.openCodeViewer();title.insertBefore(b,title.querySelector('[data-render-close="frame"]'));}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',button,{once:true});else button();window.__3DLiteAdaptiveCodeViewer3990=true;
})();</script>'''
}

marker=f'l3n-adaptive-segment-{seg}'
if marker in s: raise SystemExit(f'already has {marker}')
if seg==1:
    s=s.replace("version:'3.98.4'","version:'3.99.0'").replace("version:'3.98.3'","version:'3.99.0'",1)
    s=s.replace('3DLite v3.98.4','3DLite v3.99.0').replace('3DLite v3.98.3','3DLite v3.99.0',1)
insert=blocks[seg]
idx=s.lower().rfind('</body>')
if idx<0: raise SystemExit('no </body>')
s=s[:idx]+insert+'\n'+s[idx:]
p.write_text(s,encoding='utf-8')
print('applied segment',seg)
