(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('gl'),gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){$('status').textContent='WebGL unavailable';return}
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],norm=a=>{let l=Math.hypot(...a)||1;return[a[0]/l,a[1]/l,a[2]/l]},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const VS='attribute vec3 p,n;uniform mat4 mvp,model;varying vec3 N;void main(){N=mat3(model)*n;gl_Position=mvp*vec4(p,1.);}';const FS='precision mediump float;varying vec3 N;uniform vec3 color;uniform float sun;void main(){vec3 q=normalize(N);float d=max(dot(q,normalize(vec3(.45,1.,.35))),0.);gl_FragColor=vec4(color*(.28+d*sun),1.);}';
function sh(t,s){let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x}let pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,VS));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,FS));gl.linkProgram(pr);gl.useProgram(pr);const L={p:gl.getAttribLocation(pr,'p'),n:gl.getAttribLocation(pr,'n'),mvp:gl.getUniformLocation(pr,'mvp'),model:gl.getUniformLocation(pr,'model'),color:gl.getUniformLocation(pr,'color'),sun:gl.getUniformLocation(pr,'sun')};
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),mm=(a,b)=>{let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o},pers=(f,a,n,z)=>{let t=1/Math.tan(f/2),o=new Float32Array(16);o[0]=t/a;o[5]=t;o[10]=(z+n)/(n-z);o[11]=-1;o[14]=2*z*n/(n-z);return o};
function look(e,c){let z=norm(sub(e,c)),x=norm([z[2],0,-z[0]]),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1])}
function mesh(v){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW);return{b,c:v.length/6}}
function cube(){let p=[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],f=[[0,1,2,3,[0,0,1]],[5,4,7,6,[0,0,-1]],[4,0,3,7,[-1,0,0]],[1,5,6,2,[1,0,0]],[3,2,6,7,[0,1,0]],[4,5,1,0,[0,-1,0]]],o=[];for(let q of f)for(let i of[q[0],q[1],q[2],q[0],q[2],q[3]])o.push(...p[i],...q[4]);return mesh(o)}
function sphere(s=24,r=14){let o=[],P=(u,v)=>[Math.sin(v*Math.PI)*Math.cos(u*Math.PI*2),Math.cos(v*Math.PI),Math.sin(v*Math.PI)*Math.sin(u*Math.PI*2)];for(let y=0;y<r;y++)for(let x=0;x<s;x++){let a=P(x/s,y/r),b=P((x+1)/s,y/r),c=P((x+1)/s,(y+1)/r),d=P(x/s,(y+1)/r);for(let q of[a,b,c,a,c,d])o.push(...q,...q)}return mesh(o)}
function cone(s=24){let o=[];for(let i=0;i<s;i++){let a=i/s*Math.PI*2,b=(i+1)/s*Math.PI*2,p=[Math.cos(a),-1,Math.sin(a)],q=[Math.cos(b),-1,Math.sin(b)],n=norm([Math.cos((a+b)/2),.55,Math.sin((a+b)/2)]);for(let v of[[0,1,0],p,q])o.push(...v,...n)}return mesh(o)}
const M={cube:cube(),sphere:sphere(),cone:cone()},objects=[{name:'Cube',mesh:'cube',p:[-2,1,0],s:1,c:[.68,.72,.78],mat:'diffuse'},{name:'Gold Sphere',mesh:'sphere',p:[.3,1,0],s:1,c:[.95,.57,.08],mat:'metal'},{name:'Glass Sphere',mesh:'sphere',p:[2.7,1,0],s:1,c:[.3,.72,.95],mat:'glass'},{name:'Cone',mesh:'cone',p:[0,1,2.7],s:1,c:[.75,.29,.18],mat:'diffuse'}];
let selected=0,yaw=-.55,pitch=.35,dist=9,target=[0,1,0],pan=[0,0],wire=false;window.App3D={objects,sun:1.4,camera:()=>{let cp=Math.cos(pitch),sp=Math.sin(pitch),cy=Math.cos(yaw),sy=Math.sin(yaw),c=[target[0]+pan[0],target[1]+pan[1],target[2]],e=[c[0]+dist*cp*sy,c[1]+dist*sp,c[2]+dist*cp*cy];return{e,c}}};
function list(){let s=$('scene');s.innerHTML='';objects.forEach((o,i)=>{let d=document.createElement('div');d.className='item'+(i===selected?' sel':'');d.textContent=o.name;d.onclick=()=>{selected=i;list();sync()};s.appendChild(d)})}function sync(){let o=objects[selected];$('px').value=o.p[0];$('py').value=o.p[1];$('pz').value=o.p[2];$('sc').value=o.s;$('selName').textContent=o.name}['px','py','pz'].forEach((id,k)=>$(id).oninput=e=>objects[selected].p[k]=+e.target.value);$('sc').oninput=e=>objects[selected].s=Math.max(.1,+e.target.value);$('sun').oninput=e=>window.App3D.sun=+e.target.value;
function draw(o,v,pj){let m=I();m[0]=m[5]=m[10]=o.s;m[12]=o.p[0];m[13]=o.p[1];m[14]=o.p[2];gl.uniformMatrix4fv(L.model,false,m);gl.uniformMatrix4fv(L.mvp,false,mm(pj,mm(v,m)));gl.uniform3fv(L.color,o.c);gl.uniform1f(L.sun,window.App3D.sun);let me=M[o.mesh];gl.bindBuffer(gl.ARRAY_BUFFER,me.b);gl.enableVertexAttribArray(L.p);gl.vertexAttribPointer(L.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(L.n);gl.vertexAttribPointer(L.n,3,gl.FLOAT,false,24,12);gl.drawArrays(wire?gl.LINES:gl.TRIANGLES,0,me.c)}
let last=performance.now(),fc=0,fa=0;function loop(t){let dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight),W=w*dpr|0,H=h*dpr|0;if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H}$('size').textContent=W+'×'+H;gl.viewport(0,0,W,H);gl.enable(gl.DEPTH_TEST);gl.clearColor(.12,.13,.15,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);let C=window.App3D.camera(),v=look(C.e,C.c),pj=pers(Math.PI/4,W/H,.1,100),gm=I();gm[0]=8;gm[5]=.1;gm[10]=8;gm[13]=-.1;gl.uniformMatrix4fv(L.model,false,gm);gl.uniformMatrix4fv(L.mvp,false,mm(pj,mm(v,gm)));gl.uniform3fv(L.color,[.23,.24,.26]);gl.uniform1f(L.sun,window.App3D.sun);let me=M.cube;gl.bindBuffer(gl.ARRAY_BUFFER,me.b);gl.enableVertexAttribArray(L.p);gl.vertexAttribPointer(L.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(L.n);gl.vertexAttribPointer(L.n,3,gl.FLOAT,false,24,12);gl.drawArrays(wire?gl.LINES:gl.TRIANGLES,0,me.c);objects.forEach(o=>draw(o,v,pj));fc++;fa+=t-last;last=t;if(fa>500){$('fps').textContent=Math.round(fc*1000/fa);fc=fa=0}requestAnimationFrame(loop)}
let drag=false,mode='',mx=0,my=0;canvas.onmousedown=e=>{drag=true;mx=e.clientX;my=e.clientY;mode=(e.altKey&&e.button===0)?'orbit':e.button===1?'pan':''};window.onmouseup=()=>drag=false;window.onmousemove=e=>{if(!drag)return;let dx=e.clientX-mx,dy=e.clientY-my;mx=e.clientX;my=e.clientY;if(mode==='orbit'){yaw-=dx*.008;pitch=clamp(pitch-dy*.008,-1.3,1.3)}else if(mode==='pan'){pan[0]-=dx*.01;pan[1]+=dy*.01}};canvas.onwheel=e=>{dist=clamp(dist*Math.exp(e.deltaY*.001),2,30);e.preventDefault()};$('resetBtn').onclick=()=>{yaw=-.55;pitch=.35;dist=9;pan=[0,0];target=[0,1,0]};$('frameBtn').onclick=()=>{target=[...objects[selected].p];dist=5};$('wireBtn').onclick=()=>{wire=!wire;$('wireBtn').classList.toggle('active',wire)};$('litBtn').onclick=()=>{wire=false;$('wireBtn').classList.remove('active')};
list();sync();requestAnimationFrame(loop);$('status').textContent='Ready • WebGL viewport + Adaptive GI final renderer';
})();