(()=>{'use strict';
const $=id=>document.getElementById(id),A=()=>window.App3D;
let cancelled=false,device=null,pipeline=null;
const WGSL=`
struct Params{w:u32,h:u32,spp:u32,bounces:u32,objCount:u32,frame:u32,_p0:u32,_p1:u32,camE:vec4f,camC:vec4f,sun:vec4f};
struct Obj{posScale:vec4f,colorMat:vec4f,meta:vec4f};
struct Hit{t:f32,p:vec3f,n:vec3f,color:vec3f,mat:u32,ok:u32};
@group(0) @binding(0) var<uniform> P:Params;
@group(0) @binding(1) var<storage,read> O:array<Obj>;
@group(0) @binding(2) var<storage,read_write> Out:array<vec4f>;
fn hash(x:u32)->u32{var v=x;v^=v>>16u;v*=0x7feb352du;v^=v>>15u;v*=0x846ca68bu;v^=v>>16u;return v;}
fn rnd(s:ptr<function,u32>)->f32{*s=hash(*s+0x9e3779b9u);return f32(*s)/4294967296.0;}
fn sph(ro:vec3f,rd:vec3f,c:vec3f,r:f32)->vec2f{let oc=ro-c;let b=dot(oc,rd);let q=dot(oc,oc)-r*r;let d=b*b-q;if(d<0.0){return vec2f(-1.0,0.0);}let h=sqrt(d);var t=-b-h;if(t<0.001){t=-b+h;}if(t<0.001){return vec2f(-1.0,0.0);}return vec2f(t,1.0);}
fn boxHit(ro:vec3f,rd:vec3f,c:vec3f,s:f32)->vec4f{let mn=c-vec3f(s);let mx=c+vec3f(s);var t0=-1e20;var t1=1e20;var ax=0u;var sg=1.0;for(var i=0u;i<3u;i++){var d=rd[i];if(abs(d)<1e-8){d=select(-1e-8,1e-8,d>=0.0);}let iv=1.0/d;var a=(mn[i]-ro[i])*iv;var b=(mx[i]-ro[i])*iv;var q=-1.0;if(a>b){let z=a;a=b;b=z;q=1.0;}if(a>t0){t0=a;ax=i;sg=q;}t1=min(t1,b);if(t1<t0){return vec4f(-1.0);}}var t=t0;if(t<0.001){t=t1;}if(t<0.001){return vec4f(-1.0);}return vec4f(t,f32(ax),sg,1.0);}
fn scene(ro:vec3f,rd:vec3f)->Hit{var h:Hit;h.t=1e20;h.ok=0u;h.p=vec3f(0);h.n=vec3f(0,1,0);h.color=vec3f(0);h.mat=0u;for(var i=0u;i<P.objCount;i++){let o=O[i];let c=o.posScale.xyz;let s=o.posScale.w;let typ=u32(o.meta.x+0.5);var t=-1.0;var n=vec3f(0);if(typ==0u){let bh=boxHit(ro,rd,c,s);t=bh.x;if(t>0.0){let p=ro+rd*t;let ax=u32(bh.y+0.5);n[ax]=bh.z;}}else{let sh=sph(ro,rd,c,s);t=sh.x;if(t>0.0){let p=ro+rd*t;n=normalize(p-c);}}if(t>0.0&&t<h.t){h.t=t;h.ok=1u;h.p=ro+rd*t;h.n=n;h.color=o.colorMat.xyz;h.mat=u32(o.colorMat.w+0.5);}}
if(abs(rd.y)>1e-7){let t=-ro.y/rd.y;if(t>0.001&&t<h.t){h.t=t;h.ok=1u;h.p=ro+rd*t;h.n=vec3f(0,1,0);h.color=vec3f(.46,.46,.44);h.mat=0u;}}
return h;}
fn env(d:vec3f)->vec3f{let t=clamp(d.y*.5+.5,0.0,1.0);return mix(vec3f(.12,.14,.19),vec3f(.55,.68,.9),t);}
fn hemi(n:vec3f,s:ptr<function,u32>)->vec3f{let a=select(vec3f(1,0,0),vec3f(0,1,0),abs(n.y)<.9);let t=normalize(cross(a,n));let b=cross(n,t);let u=rnd(s);let v=rnd(s);let rr=sqrt(u);let th=6.2831853*v;return normalize(t*(rr*cos(th))+n*sqrt(max(0.0,1.0-u))+b*(rr*sin(th)));}
fn visible(p:vec3f,n:vec3f,l:vec3f)->f32{let q=scene(p+n*.001,l);return select(1.0,0.0,q.ok==1u);}
fn trace(ro0:vec3f,rd0:vec3f,s:ptr<function,u32>)->vec3f{var ro=ro0;var rd=rd0;var tp=vec3f(1);var L=vec3f(0);let ld=normalize(vec3f(.45,1,.35));for(var depth=0u;depth<8u;depth++){if(depth>P.bounces){break;}let h=scene(ro,rd);if(h.ok==0u){L+=tp*env(rd);break;}let nd=max(0.0,dot(h.n,ld));let vis=visible(h.p,h.n,ld);let direct=h.color*(.08+.10*max(0.0,h.n.y)+nd*P.sun.x*vis);L+=tp*direct;if(depth==P.bounces){break;}if(h.mat==1u){rd=normalize(reflect(rd,h.n)+hemi(h.n,s)*.08);tp*=h.color*.92;ro=h.p+h.n*.001;}else if(h.mat==2u){var nn=h.n;var eta=1.0/1.5;var co=-dot(rd,nn);if(co<0.0){nn=-nn;eta=1.5;co=-dot(rd,nn);}let r0=.04;let fr=r0+(1.0-r0)*pow(1.0-clamp(co,0.0,1.0),5.0);let refrd=refract(rd,nn,eta);let useR=rnd(s)<fr||length(refrd)<.001;rd=select(refrd,reflect(rd,nn),useR);ro=h.p+nn*select(-.001,.001,useR);tp*=vec3f(.97);}else{rd=hemi(h.n,s);tp*=h.color*.62;ro=h.p+h.n*.001;}if(max(tp.x,max(tp.y,tp.z))<.025){break;}}
return L;}
@compute @workgroup_size(8,8)
fn main(@builtin(global_invocation_id) gid:vec3u){if(gid.x>=P.w||gid.y>=P.h){return;}let idx=gid.y*P.w+gid.x;var seed=hash(idx+P.frame*1664525u+1013904223u);let f=normalize(P.camC.xyz-P.camE.xyz);let r=normalize(cross(f,vec3f(0,1,0)));let u=cross(r,f);let asp=f32(P.w)/f32(P.h);let tn=tan(3.14159265/8.0);var sum=vec3f(0);for(var s=0u;s<P.spp;s++){let jx=rnd(&seed);let jy=rnd(&seed);let sx=((f32(gid.x)+jx)/f32(P.w)*2.0-1.0)*asp*tn;let sy=(1.0-(f32(gid.y)+jy)/f32(P.h)*2.0)*tn;let rd=normalize(f+r*sx+u*sy);sum+=trace(P.camE.xyz,rd,&seed);}Out[idx]=vec4f(sum/f32(max(P.spp,1u)),1.0);}`;
async function init(){if(device)return true;if(!navigator.gpu)return false;const a=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!a)return false;device=await a.requestDevice();const mod=device.createShaderModule({code:WGSL});const info=await mod.getCompilationInfo();if(info.messages.some(m=>m.type==='error')){console.error('R3D WebGPU WGSL',info.messages);device=null;return false;}pipeline=device.createComputePipeline({layout:'auto',compute:{module:mod,entryPoint:'main'}});return true;}
function objData(){const a=A(),arr=new Float32Array(Math.max(1,a.objects.length)*12);a.objects.forEach((o,i)=>{let k=i*12,typ=o.mesh==='cube'?0:1,mat=o.mat==='metal'?1:o.mat==='glass'?2:0;arr.set([o.p[0],o.p[1],o.p[2],o.s,o.c[0],o.c[1],o.c[2],mat,typ,0,0,0],k)});return arr;}
async function render(){cancelled=false;if(!await init())return false;const outW=+$('rw').value,outH=Math.round(outW*.625),scale=+$('rscale').value,w=Math.max(96,Math.round(outW*scale)),h=Math.max(60,Math.round(outH*scale)),spp=Math.max(1,+$('samples').value),bounces=Math.max(0,+$('bounces').value),cam=A().camera(),objs=objData(),start=performance.now();$('modal').style.display='flex';$('renderInfo').textContent=`R3D WebGPU GI • ${w}×${h} → ${outW}×${outH} • ${spp} spp • ${bounces} bounces`;$('bar').style.width='8%';$('pct').textContent='8%';
const params=new ArrayBuffer(96),dv=new DataView(params);let u32=(o,v)=>dv.setUint32(o,v,true),f32=(o,v)=>dv.setFloat32(o,v,true);u32(0,w);u32(4,h);u32(8,spp);u32(12,bounces);u32(16,A().objects.length);u32(20,(performance.now()*1000)>>>0);[...cam.e,1,...cam.c,1,A().sun,0,0,0].forEach((v,i)=>f32(32+i*4,v));
const pbuf=device.createBuffer({size:96,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(pbuf,0,params);const osz=Math.max(48,objs.byteLength),obuf=device.createBuffer({size:osz,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(obuf,0,objs);const bytes=w*h*16,out=device.createBuffer({size:bytes,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC}),read=device.createBuffer({size:bytes,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:pbuf}},{binding:1,resource:{buffer:obuf}},{binding:2,resource:{buffer:out}}]});const enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.dispatchWorkgroups(Math.ceil(w/8),Math.ceil(h/8));pass.end();enc.copyBufferToBuffer(out,0,read,0,bytes);device.queue.submit([enc.finish()]);$('bar').style.width='55%';$('pct').textContent='55%';await read.mapAsync(GPUMapMode.READ);if(cancelled){read.unmap();return true;}const src=new Float32Array(read.getMappedRange().slice(0));read.unmap();$('bar').style.width='82%';$('pct').textContent='82%';
const tmp=document.createElement('canvas');tmp.width=w;tmp.height=h;const tc=tmp.getContext('2d'),im=tc.createImageData(w,h);for(let i=0;i<w*h;i++){for(let c=0;c<3;c++){let v=src[i*4+c];v=v/(1+v);im.data[i*4+c]=Math.round(Math.pow(Math.max(0,Math.min(1,v)),1/2.2)*255);}im.data[i*4+3]=255;}tc.putImageData(im,0,0);const rc=$('rc'),ctx=rc.getContext('2d');rc.width=outW;rc.height=outH;ctx.imageSmoothingEnabled=$('recon').value==='1';ctx.imageSmoothingQuality='high';ctx.drawImage(tmp,0,0,outW,outH);$('bar').style.width='100%';$('pct').textContent='100%';$('stats').textContent=`WebGPU full ray traversal • ${(w*h*spp).toLocaleString()} primary samples • ${((performance.now()-start)/1000).toFixed(2)}s`;$('renderInfo').textContent='R3D WebGPU GI complete';return true;}
window.R3DWebGPU={render,cancel:()=>cancelled=true,available:()=>!!navigator.gpu};
})();